In [1]:
import pandas as pd
import regex as re
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

In [2]:
disneylive = pd.read_csv('data/live.csv')

In [3]:
disneymarvel = pd.read_csv('data/marvel.csv')

In [4]:
disneypixar = pd.read_csv('data/pixar.csv')

In [5]:
disneyspiderman = pd.read_csv('data/spiderman.csv')

In [6]:
disneystarwars = pd.read_csv('data/starwars.csv')

In [7]:
disneywdanimation = pd.read_csv('data/wdanimation.csv')

In [8]:
disneylive

,Unnamed: 0,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False
1,1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False
2,2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False
3,3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False
4,4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False
5,5,6,Maleficent,"$241,410,378",3948,"$69,431,298",3948,"May 30, 2014",Walt Disney Studios Motion Pictures,False
6,6,7,Oz the Great and Powerful,"$234,911,825",3912,"$79,110,453",3912,"Mar 8, 2013",Walt Disney Studios Motion Pictures,False
7,7,8,Cinderella,"$201,151,353",3848,"$67,877,361",3845,"Mar 13, 2015",Walt Disney Studios Motion Pictures,False
8,8,9,101 Dalmatians,"$136,189,294",2901,"$33,504,025",2794,"Nov 27, 1996",Walt Disney Studios Motion Pictures,False
9,9,10,Dumbo,"$114,766,307",4259,"$45,990,748",4259,"Mar 29, 2019",Walt Disney Studios Motion Pictures,False
10,10,11,Maleficent: Mistress of Evil,"$113,929,605",3820,"$36,948,713",3790,"Oct 18, 2019",Walt Disney Studios Motion Pictures,False
11,11,12,Cruella,"$86,103,234",3922,"$21,496,997",3892,"May 28, 2021",Walt Disney Studios Motion Pictures,False
12,12,13,Alice Through the Looking Glass,"$77,041,381",3763,"$26,858,726",3763,"May 27, 2016",Walt Disney Studios Motion Pictures,False
13,13,14,Pete's Dragon,"$76,233,151",3702,"$21,514,095",3702,"Aug 12, 2016",Walt Disney Studios Motion Pictures,False
14,14,15,102 Dalmatians,"$66,957,026",2704,"$19,883,351",2704,"Nov 22, 2000",Walt Disney Studios Motion Pictures,False
15,15,16,The Jungle Book,"$43,229,904",2012,"$5,129,959",1880,"Dec 25, 1994",Walt Disney Studios Motion Pictures,False
16,16,17,Beauty and the Beast2020 Re-release,"$467,000",527,"$467,000",527,"Jul 17, 2020",Walt Disney Pictures,True
17,17,-,Mulan,-,-,-,-,-,Walt Disney Studios Motion Pictures,False

In [9]:
disneylive.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      18 non-null     int64
 1   Rank            18 non-null     object
 2   Release         18 non-null     object
 3   Lifetime Gross  18 non-null     object
 4   Max Theaters    18 non-null     object
 5   Opening         18 non-null     object
 6   Open Th         18 non-null     object
 7   Release Date    18 non-null     object
 8   Distributor     18 non-null     object
 9   Estimated       18 non-null     bool
dtypes: bool(1), int64(1), object(8)
memory usage: 1.4+ KB

In [10]:
disneylive=disneylive.drop(['Unnamed: 0'], axis=1)
disneylive

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False
1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False
2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False
3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False
4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False
5,6,Maleficent,"$241,410,378",3948,"$69,431,298",3948,"May 30, 2014",Walt Disney Studios Motion Pictures,False
6,7,Oz the Great and Powerful,"$234,911,825",3912,"$79,110,453",3912,"Mar 8, 2013",Walt Disney Studios Motion Pictures,False
7,8,Cinderella,"$201,151,353",3848,"$67,877,361",3845,"Mar 13, 2015",Walt Disney Studios Motion Pictures,False
8,9,101 Dalmatians,"$136,189,294",2901,"$33,504,025",2794,"Nov 27, 1996",Walt Disney Studios Motion Pictures,False
9,10,Dumbo,"$114,766,307",4259,"$45,990,748",4259,"Mar 29, 2019",Walt Disney Studios Motion Pictures,False
10,11,Maleficent: Mistress of Evil,"$113,929,605",3820,"$36,948,713",3790,"Oct 18, 2019",Walt Disney Studios Motion Pictures,False
11,12,Cruella,"$86,103,234",3922,"$21,496,997",3892,"May 28, 2021",Walt Disney Studios Motion Pictures,False
12,13,Alice Through the Looking Glass,"$77,041,381",3763,"$26,858,726",3763,"May 27, 2016",Walt Disney Studios Motion Pictures,False
13,14,Pete's Dragon,"$76,233,151",3702,"$21,514,095",3702,"Aug 12, 2016",Walt Disney Studios Motion Pictures,False
14,15,102 Dalmatians,"$66,957,026",2704,"$19,883,351",2704,"Nov 22, 2000",Walt Disney Studios Motion Pictures,False
15,16,The Jungle Book,"$43,229,904",2012,"$5,129,959",1880,"Dec 25, 1994",Walt Disney Studios Motion Pictures,False
16,17,Beauty and the Beast2020 Re-release,"$467,000",527,"$467,000",527,"Jul 17, 2020",Walt Disney Pictures,True
17,-,Mulan,-,-,-,-,-,Walt Disney Studios Motion Pictures,False

In [11]:
disneylive=disneylive.drop(disneylive.index[17:])
disneylive

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False
1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False
2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False
3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False
4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False
5,6,Maleficent,"$241,410,378",3948,"$69,431,298",3948,"May 30, 2014",Walt Disney Studios Motion Pictures,False
6,7,Oz the Great and Powerful,"$234,911,825",3912,"$79,110,453",3912,"Mar 8, 2013",Walt Disney Studios Motion Pictures,False
7,8,Cinderella,"$201,151,353",3848,"$67,877,361",3845,"Mar 13, 2015",Walt Disney Studios Motion Pictures,False
8,9,101 Dalmatians,"$136,189,294",2901,"$33,504,025",2794,"Nov 27, 1996",Walt Disney Studios Motion Pictures,False
9,10,Dumbo,"$114,766,307",4259,"$45,990,748",4259,"Mar 29, 2019",Walt Disney Studios Motion Pictures,False
10,11,Maleficent: Mistress of Evil,"$113,929,605",3820,"$36,948,713",3790,"Oct 18, 2019",Walt Disney Studios Motion Pictures,False
11,12,Cruella,"$86,103,234",3922,"$21,496,997",3892,"May 28, 2021",Walt Disney Studios Motion Pictures,False
12,13,Alice Through the Looking Glass,"$77,041,381",3763,"$26,858,726",3763,"May 27, 2016",Walt Disney Studios Motion Pictures,False
13,14,Pete's Dragon,"$76,233,151",3702,"$21,514,095",3702,"Aug 12, 2016",Walt Disney Studios Motion Pictures,False
14,15,102 Dalmatians,"$66,957,026",2704,"$19,883,351",2704,"Nov 22, 2000",Walt Disney Studios Motion Pictures,False
15,16,The Jungle Book,"$43,229,904",2012,"$5,129,959",1880,"Dec 25, 1994",Walt Disney Studios Motion Pictures,False
16,17,Beauty and the Beast2020 Re-release,"$467,000",527,"$467,000",527,"Jul 17, 2020",Walt Disney Pictures,True

In [12]:
disneymarvel

,Unnamed: 0,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,0,1,Avengers: Endgame,"$858,373,000",4662,"$357,115,007",4662,"Apr 26, 2019",Walt Disney Studios Motion Pictures,False
1,1,2,Spider-Man: No Way Home,"$804,793,477",4336,"$260,138,569",4336,"Dec 17, 2021",Sony Pictures Entertainment (SPE),False
2,2,3,Black Panther,"$700,059,566",4084,"$202,003,951",4020,"Feb 16, 2018",Walt Disney Studios Motion Pictures,False
3,3,4,Avengers: Infinity War,"$678,815,482",4474,"$257,698,183",4474,"Apr 27, 2018",Walt Disney Studios Motion Pictures,False
4,4,5,The Avengers,"$623,357,910",4349,"$207,438,708",4349,"May 4, 2012",Walt Disney Studios Motion Pictures,False
5,5,6,Avengers: Age of Ultron,"$459,005,868",4276,"$191,271,109",4276,"May 1, 2015",Walt Disney Studios Motion Pictures,False
6,6,7,Black Panther: Wakanda Forever,"$453,829,060",4396,"$181,339,761",4396,"Nov 11, 2022",Walt Disney Studios Motion Pictures,False
7,7,8,Captain Marvel,"$426,829,839",4310,"$153,433,423",4310,"Mar 8, 2019",Walt Disney Studios Motion Pictures,False
8,8,9,Doctor Strange in the Multiverse of Madness,"$411,331,607",4534,"$187,420,998",4534,"May 6, 2022",Walt Disney Studios Motion Pictures,False
9,9,10,Iron Man 3,"$409,013,994",4253,"$174,144,585",4253,"May 3, 2013",Walt Disney Studios Motion Pictures,False
10,10,11,Captain America: Civil War,"$408,084,349",4226,"$179,139,142",4226,"May 6, 2016",Walt Disney Studios Motion Pictures,False
11,11,12,Spider-Man: Far from Home,"$390,532,085",4634,"$92,579,212",4634,"Jul 2, 2019",Sony Pictures Entertainment (SPE),False
12,12,13,Guardians of the Galaxy Vol. 2,"$389,813,101",4347,"$146,510,104",4347,"May 5, 2017",Walt Disney Studios Motion Pictures,False
13,13,14,Guardians of the Galaxy Vol. 3,"$356,577,614",4450,"$118,414,021",4450,"May 5, 2023",Walt Disney Studios Motion Pictures,False
14,14,15,Thor: Love and Thunder,"$343,256,830",4375,"$144,165,107",4375,"Jul 8, 2022",Walt Disney Studios Motion Pictures,False
15,15,16,Spider-Man: Homecoming,"$334,201,140",4348,"$117,027,503",4348,"Jul 7, 2017",Sony Pictures Entertainment (SPE),False
16,16,17,Guardians of the Galaxy,"$333,176,600",4088,"$94,320,883",4080,"Aug 1, 2014",Walt Disney Studios Motion Pictures,False
17,17,18,Iron Man,"$318,604,126",4154,"$98,618,668",4105,"May 2, 2008",Paramount Pictures,False
18,18,19,Thor: Ragnarok,"$315,058,289",4080,"$122,744,989",4080,"Nov 3, 2017",Walt Disney Studios Motion Pictures,False
19,19,20,Iron Man 2,"$312,433,331",4390,"$128,122,480",4380,"May 7, 2010",Paramount Pictures,False
20,20,21,Captain America: The Winter Soldier,"$259,766,572",3938,"$95,023,721",3938,"Apr 4, 2014",Walt Disney Studios Motion Pictures,False
21,21,22,Doctor Strange,"$232,641,920",3882,"$85,058,311",3882,"Nov 4, 2016",Walt Disney Studios Motion Pictures,False
22,22,23,Shang-Chi and the Legend of the Ten Rings,"$224,543,292",4300,"$75,388,688",4300,"Sep 3, 2021",Walt Disney Studios Motion Pictures,False
23,23,24,Ant-Man and the Wasp,"$216,648,740",4206,"$75,812,205",4206,"Jul 6, 2018",Walt Disney Studios Motion Pictures,False
24,24,25,Ant-Man and the Wasp: Quantumania,"$214,504,909",4345,"$106,109,650",4345,"Feb 17, 2023",Walt Disney Studios Motion Pictures,False
25,25,26,Thor: The Dark World,"$206,362,140",3841,"$85,737,841",3841,"Nov 8, 2013",Walt Disney Studios Motion Pictures,False
26,26,27,Black Widow,"$183,651,655",4275,"$80,366,312",4160,"Jul 9, 2021",Walt Disney Studios Motion Pictures,False
27,27,28,Thor,"$181,030,624",3963,"$65,723,338",3955,"May 6, 2011",Paramount Pictures,False
28,28,29,Ant-Man,"$180,202,163",3868,"$57,225,526",3856,"Jul 17, 2015",Walt Disney Studios Motion Pictures,False
29,29,30,Captain America: The First Avenger,"$176,654,505",3715,"$65,058,524",3715,"Jul 22, 2011",Paramount Pictures,False
30,30,31,Eternals,"$164,870,234",4090,"$71,297,219",4090,"Nov 5, 2021",Walt Disney Studios Motion Pictures,False
31,31,32,The Incredible Hulk,"$134,806,913",3508,"$55,414,050",3505,"Jun 13, 2008",Universal Pictures,False
32,32,33,Spider-Man: No Way Home2022 Re-release,"$9,321,593",3935,"$5,403,230",3935,"Sep 2, 2022",Sony Pictures Entertainment (SPE),False
33,33,34,Guardians of the Galaxy2020 Re-release,"$542,000",1560,"$406,000",1560,"Nov 13, 2020",Walt Disney Studios Motion Pictures,True
34,34,35,Iron Man2020 Re-release,"$430,000",462,"$430,000",462,"Jul 17, 2020",Walt Disney Pictures,True
35,35,36,Black Panther2020 Re-release,"$367,000",421,"$367,000",421,"Jul 10, 2020",Walt Disney Pictures,True
36,36,-,Black WidowStreaming - PVOD,-,-,-,-,"Jul 9, 2021",Walt Disney Studios Motion Pictures,False
37,37,-,The Marvels,-,-,-,-,"Nov 10, 2023",Walt Disney Studios Motion Pictures,False

In [13]:
disneymarvel=disneymarvel.drop(['Unnamed: 0'], axis=1)
disneymarvel

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Avengers: Endgame,"$858,373,000",4662,"$357,115,007",4662,"Apr 26, 2019",Walt Disney Studios Motion Pictures,False
1,2,Spider-Man: No Way Home,"$804,793,477",4336,"$260,138,569",4336,"Dec 17, 2021",Sony Pictures Entertainment (SPE),False
2,3,Black Panther,"$700,059,566",4084,"$202,003,951",4020,"Feb 16, 2018",Walt Disney Studios Motion Pictures,False
3,4,Avengers: Infinity War,"$678,815,482",4474,"$257,698,183",4474,"Apr 27, 2018",Walt Disney Studios Motion Pictures,False
4,5,The Avengers,"$623,357,910",4349,"$207,438,708",4349,"May 4, 2012",Walt Disney Studios Motion Pictures,False
5,6,Avengers: Age of Ultron,"$459,005,868",4276,"$191,271,109",4276,"May 1, 2015",Walt Disney Studios Motion Pictures,False
6,7,Black Panther: Wakanda Forever,"$453,829,060",4396,"$181,339,761",4396,"Nov 11, 2022",Walt Disney Studios Motion Pictures,False
7,8,Captain Marvel,"$426,829,839",4310,"$153,433,423",4310,"Mar 8, 2019",Walt Disney Studios Motion Pictures,False
8,9,Doctor Strange in the Multiverse of Madness,"$411,331,607",4534,"$187,420,998",4534,"May 6, 2022",Walt Disney Studios Motion Pictures,False
9,10,Iron Man 3,"$409,013,994",4253,"$174,144,585",4253,"May 3, 2013",Walt Disney Studios Motion Pictures,False
10,11,Captain America: Civil War,"$408,084,349",4226,"$179,139,142",4226,"May 6, 2016",Walt Disney Studios Motion Pictures,False
11,12,Spider-Man: Far from Home,"$390,532,085",4634,"$92,579,212",4634,"Jul 2, 2019",Sony Pictures Entertainment (SPE),False
12,13,Guardians of the Galaxy Vol. 2,"$389,813,101",4347,"$146,510,104",4347,"May 5, 2017",Walt Disney Studios Motion Pictures,False
13,14,Guardians of the Galaxy Vol. 3,"$356,577,614",4450,"$118,414,021",4450,"May 5, 2023",Walt Disney Studios Motion Pictures,False
14,15,Thor: Love and Thunder,"$343,256,830",4375,"$144,165,107",4375,"Jul 8, 2022",Walt Disney Studios Motion Pictures,False
15,16,Spider-Man: Homecoming,"$334,201,140",4348,"$117,027,503",4348,"Jul 7, 2017",Sony Pictures Entertainment (SPE),False
16,17,Guardians of the Galaxy,"$333,176,600",4088,"$94,320,883",4080,"Aug 1, 2014",Walt Disney Studios Motion Pictures,False
17,18,Iron Man,"$318,604,126",4154,"$98,618,668",4105,"May 2, 2008",Paramount Pictures,False
18,19,Thor: Ragnarok,"$315,058,289",4080,"$122,744,989",4080,"Nov 3, 2017",Walt Disney Studios Motion Pictures,False
19,20,Iron Man 2,"$312,433,331",4390,"$128,122,480",4380,"May 7, 2010",Paramount Pictures,False
20,21,Captain America: The Winter Soldier,"$259,766,572",3938,"$95,023,721",3938,"Apr 4, 2014",Walt Disney Studios Motion Pictures,False
21,22,Doctor Strange,"$232,641,920",3882,"$85,058,311",3882,"Nov 4, 2016",Walt Disney Studios Motion Pictures,False
22,23,Shang-Chi and the Legend of the Ten Rings,"$224,543,292",4300,"$75,388,688",4300,"Sep 3, 2021",Walt Disney Studios Motion Pictures,False
23,24,Ant-Man and the Wasp,"$216,648,740",4206,"$75,812,205",4206,"Jul 6, 2018",Walt Disney Studios Motion Pictures,False
24,25,Ant-Man and the Wasp: Quantumania,"$214,504,909",4345,"$106,109,650",4345,"Feb 17, 2023",Walt Disney Studios Motion Pictures,False
25,26,Thor: The Dark World,"$206,362,140",3841,"$85,737,841",3841,"Nov 8, 2013",Walt Disney Studios Motion Pictures,False
26,27,Black Widow,"$183,651,655",4275,"$80,366,312",4160,"Jul 9, 2021",Walt Disney Studios Motion Pictures,False
27,28,Thor,"$181,030,624",3963,"$65,723,338",3955,"May 6, 2011",Paramount Pictures,False
28,29,Ant-Man,"$180,202,163",3868,"$57,225,526",3856,"Jul 17, 2015",Walt Disney Studios Motion Pictures,False
29,30,Captain America: The First Avenger,"$176,654,505",3715,"$65,058,524",3715,"Jul 22, 2011",Paramount Pictures,False
30,31,Eternals,"$164,870,234",4090,"$71,297,219",4090,"Nov 5, 2021",Walt Disney Studios Motion Pictures,False
31,32,The Incredible Hulk,"$134,806,913",3508,"$55,414,050",3505,"Jun 13, 2008",Universal Pictures,False
32,33,Spider-Man: No Way Home2022 Re-release,"$9,321,593",3935,"$5,403,230",3935,"Sep 2, 2022",Sony Pictures Entertainment (SPE),False
33,34,Guardians of the Galaxy2020 Re-release,"$542,000",1560,"$406,000",1560,"Nov 13, 2020",Walt Disney Studios Motion Pictures,True
34,35,Iron Man2020 Re-release,"$430,000",462,"$430,000",462,"Jul 17, 2020",Walt Disney Pictures,True
35,36,Black Panther2020 Re-release,"$367,000",421,"$367,000",421,"Jul 10, 2020",Walt Disney Pictures,True
36,-,Black WidowStreaming - PVOD,-,-,-,-,"Jul 9, 2021",Walt Disney Studios Motion Pictures,False
37,-,The Marvels,-,-,-,-,"Nov 10, 2023",Walt Disney Studios Motion Pictures,False

In [14]:
disneymarvel=disneymarvel.drop(disneymarvel.index[32:])

In [15]:
disneymarvel

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Avengers: Endgame,"$858,373,000",4662,"$357,115,007",4662,"Apr 26, 2019",Walt Disney Studios Motion Pictures,False
1,2,Spider-Man: No Way Home,"$804,793,477",4336,"$260,138,569",4336,"Dec 17, 2021",Sony Pictures Entertainment (SPE),False
2,3,Black Panther,"$700,059,566",4084,"$202,003,951",4020,"Feb 16, 2018",Walt Disney Studios Motion Pictures,False
3,4,Avengers: Infinity War,"$678,815,482",4474,"$257,698,183",4474,"Apr 27, 2018",Walt Disney Studios Motion Pictures,False
4,5,The Avengers,"$623,357,910",4349,"$207,438,708",4349,"May 4, 2012",Walt Disney Studios Motion Pictures,False
5,6,Avengers: Age of Ultron,"$459,005,868",4276,"$191,271,109",4276,"May 1, 2015",Walt Disney Studios Motion Pictures,False
6,7,Black Panther: Wakanda Forever,"$453,829,060",4396,"$181,339,761",4396,"Nov 11, 2022",Walt Disney Studios Motion Pictures,False
7,8,Captain Marvel,"$426,829,839",4310,"$153,433,423",4310,"Mar 8, 2019",Walt Disney Studios Motion Pictures,False
8,9,Doctor Strange in the Multiverse of Madness,"$411,331,607",4534,"$187,420,998",4534,"May 6, 2022",Walt Disney Studios Motion Pictures,False
9,10,Iron Man 3,"$409,013,994",4253,"$174,144,585",4253,"May 3, 2013",Walt Disney Studios Motion Pictures,False
10,11,Captain America: Civil War,"$408,084,349",4226,"$179,139,142",4226,"May 6, 2016",Walt Disney Studios Motion Pictures,False
11,12,Spider-Man: Far from Home,"$390,532,085",4634,"$92,579,212",4634,"Jul 2, 2019",Sony Pictures Entertainment (SPE),False
12,13,Guardians of the Galaxy Vol. 2,"$389,813,101",4347,"$146,510,104",4347,"May 5, 2017",Walt Disney Studios Motion Pictures,False
13,14,Guardians of the Galaxy Vol. 3,"$356,577,614",4450,"$118,414,021",4450,"May 5, 2023",Walt Disney Studios Motion Pictures,False
14,15,Thor: Love and Thunder,"$343,256,830",4375,"$144,165,107",4375,"Jul 8, 2022",Walt Disney Studios Motion Pictures,False
15,16,Spider-Man: Homecoming,"$334,201,140",4348,"$117,027,503",4348,"Jul 7, 2017",Sony Pictures Entertainment (SPE),False
16,17,Guardians of the Galaxy,"$333,176,600",4088,"$94,320,883",4080,"Aug 1, 2014",Walt Disney Studios Motion Pictures,False
17,18,Iron Man,"$318,604,126",4154,"$98,618,668",4105,"May 2, 2008",Paramount Pictures,False
18,19,Thor: Ragnarok,"$315,058,289",4080,"$122,744,989",4080,"Nov 3, 2017",Walt Disney Studios Motion Pictures,False
19,20,Iron Man 2,"$312,433,331",4390,"$128,122,480",4380,"May 7, 2010",Paramount Pictures,False
20,21,Captain America: The Winter Soldier,"$259,766,572",3938,"$95,023,721",3938,"Apr 4, 2014",Walt Disney Studios Motion Pictures,False
21,22,Doctor Strange,"$232,641,920",3882,"$85,058,311",3882,"Nov 4, 2016",Walt Disney Studios Motion Pictures,False
22,23,Shang-Chi and the Legend of the Ten Rings,"$224,543,292",4300,"$75,388,688",4300,"Sep 3, 2021",Walt Disney Studios Motion Pictures,False
23,24,Ant-Man and the Wasp,"$216,648,740",4206,"$75,812,205",4206,"Jul 6, 2018",Walt Disney Studios Motion Pictures,False
24,25,Ant-Man and the Wasp: Quantumania,"$214,504,909",4345,"$106,109,650",4345,"Feb 17, 2023",Walt Disney Studios Motion Pictures,False
25,26,Thor: The Dark World,"$206,362,140",3841,"$85,737,841",3841,"Nov 8, 2013",Walt Disney Studios Motion Pictures,False
26,27,Black Widow,"$183,651,655",4275,"$80,366,312",4160,"Jul 9, 2021",Walt Disney Studios Motion Pictures,False
27,28,Thor,"$181,030,624",3963,"$65,723,338",3955,"May 6, 2011",Paramount Pictures,False
28,29,Ant-Man,"$180,202,163",3868,"$57,225,526",3856,"Jul 17, 2015",Walt Disney Studios Motion Pictures,False
29,30,Captain America: The First Avenger,"$176,654,505",3715,"$65,058,524",3715,"Jul 22, 2011",Paramount Pictures,False
30,31,Eternals,"$164,870,234",4090,"$71,297,219",4090,"Nov 5, 2021",Walt Disney Studios Motion Pictures,False
31,32,The Incredible Hulk,"$134,806,913",3508,"$55,414,050",3505,"Jun 13, 2008",Universal Pictures,False

In [16]:
disneylive['category'] = 'live reimaginings'

In [17]:
disneymarvel['category'] = 'marvel'

In [18]:
livemarvel = pd.concat([disneylive, disneymarvel])
livemarvel

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False,live reimaginings
2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False,live reimaginings
5,6,Maleficent,"$241,410,378",3948,"$69,431,298",3948,"May 30, 2014",Walt Disney Studios Motion Pictures,False,live reimaginings
6,7,Oz the Great and Powerful,"$234,911,825",3912,"$79,110,453",3912,"Mar 8, 2013",Walt Disney Studios Motion Pictures,False,live reimaginings
7,8,Cinderella,"$201,151,353",3848,"$67,877,361",3845,"Mar 13, 2015",Walt Disney Studios Motion Pictures,False,live reimaginings
8,9,101 Dalmatians,"$136,189,294",2901,"$33,504,025",2794,"Nov 27, 1996",Walt Disney Studios Motion Pictures,False,live reimaginings
9,10,Dumbo,"$114,766,307",4259,"$45,990,748",4259,"Mar 29, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
10,11,Maleficent: Mistress of Evil,"$113,929,605",3820,"$36,948,713",3790,"Oct 18, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
11,12,Cruella,"$86,103,234",3922,"$21,496,997",3892,"May 28, 2021",Walt Disney Studios Motion Pictures,False,live reimaginings
12,13,Alice Through the Looking Glass,"$77,041,381",3763,"$26,858,726",3763,"May 27, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
13,14,Pete's Dragon,"$76,233,151",3702,"$21,514,095",3702,"Aug 12, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
14,15,102 Dalmatians,"$66,957,026",2704,"$19,883,351",2704,"Nov 22, 2000",Walt Disney Studios Motion Pictures,False,live reimaginings
15,16,The Jungle Book,"$43,229,904",2012,"$5,129,959",1880,"Dec 25, 1994",Walt Disney Studios Motion Pictures,False,live reimaginings
16,17,Beauty and the Beast2020 Re-release,"$467,000",527,"$467,000",527,"Jul 17, 2020",Walt Disney Pictures,True,live reimaginings
0,1,Avengers: Endgame,"$858,373,000",4662,"$357,115,007",4662,"Apr 26, 2019",Walt Disney Studios Motion Pictures,False,marvel
1,2,Spider-Man: No Way Home,"$804,793,477",4336,"$260,138,569",4336,"Dec 17, 2021",Sony Pictures Entertainment (SPE),False,marvel
2,3,Black Panther,"$700,059,566",4084,"$202,003,951",4020,"Feb 16, 2018",Walt Disney Studios Motion Pictures,False,marvel
3,4,Avengers: Infinity War,"$678,815,482",4474,"$257,698,183",4474,"Apr 27, 2018",Walt Disney Studios Motion Pictures,False,marvel
4,5,The Avengers,"$623,357,910",4349,"$207,438,708",4349,"May 4, 2012",Walt Disney Studios Motion Pictures,False,marvel
5,6,Avengers: Age of Ultron,"$459,005,868",4276,"$191,271,109",4276,"May 1, 2015",Walt Disney Studios Motion Pictures,False,marvel
6,7,Black Panther: Wakanda Forever,"$453,829,060",4396,"$181,339,761",4396,"Nov 11, 2022",Walt Disney Studios Motion Pictures,False,marvel
7,8,Captain Marvel,"$426,829,839",4310,"$153,433,423",4310,"Mar 8, 2019",Walt Disney Studios Motion Pictures,False,marvel
8,9,Doctor Strange in the Multiverse of Madness,"$411,331,607",4534,"$187,420,998",4534,"May 6, 2022",Walt Disney Studios Motion Pictures,False,marvel
9,10,Iron Man 3,"$409,013,994",4253,"$174,144,585",4253,"May 3, 2013",Walt Disney Studios Motion Pictures,False,marvel
10,11,Captain America: Civil War,"$408,084,349",4226,"$179,139,142",4226,"May 6, 2016",Walt Disney Studios Motion Pictures,False,marvel
11,12,Spider-Man: Far from Home,"$390,532,085",4634,"$92,579,212",4634,"Jul 2, 2019",Sony Pictures Entertainment (SPE),False,marvel
12,13,Guardians of the Galaxy Vol. 2,"$389,813,101",4347,"$146,510,104",4347,"May 5, 2017",Walt Disney Studios Motion Pictures,False,marvel
13,14,Guardians of the Galaxy Vol. 3,"$356,577,614",4450,"$118,414,021",4450,"May 5, 2023",Walt Disney Studios Motion Pictures,False,marvel
14,15,Thor: Love and Thunder,"$343,256,830",4375,"$144,165,107",4375,"Jul 8, 2022",Walt Disney Studios Motion Pictures,False,marvel
15,16,Spider-Man: Homecoming,"$334,201,140",4348,"$117,027,503",4348,"Jul 7, 2017",Sony Pictures Entertainment (SPE),False,marvel
16,17,Guardians of the Galaxy,"$333,176,600",4088,"$94,320,883",4080,"Aug 1, 2014",Walt Disney Studios Motion Pictures,False,marvel
17,18,Iron Man,"$318,604,126",4154,"$98,618,668",4105,"May 2, 2008",Paramount Pictures,False,marvel
18,19,Thor: Ragnarok,"$315,058,289",4080,"$122,744,989",4080,"Nov 3, 2017",Walt Disney Studios Motion Pictures,False,marvel
19,20,Iron Man 2,"$312,433,331",4390,"$128,122,480",4380,"May 7, 2010",Paramount Pictures,False,marvel
20,21,Captain America: The Winter Soldier,"$259,766,572",3938,"$95,023,721",3938,"Apr 4, 2014",Walt Disney Studios Motion Pictures,False,marvel
21,22,Doctor Strange,"$232,641,920",3882,"$85,058,311",3882,"Nov 4, 2016",Walt Disney Studios Motion Pictures,False,marvel
22,23,Shang-Chi and the Legend of the Ten Rings,"$224,543,292",4300,"$75,388,688",4300,"Sep 3, 2021",Walt Disney Studios Motion Pictures,False,marvel
23,24,Ant-Man and the Wasp,"$216,648,740",4206,"$75,812,205",4206,"Jul 6, 2018",Walt Disney Studios Motion Pictures,False,marvel
24,25,Ant-Man and the Wasp: Quantumania,"$214,504,909",4345,"$106,109,650",4345,"Feb 17, 2023",Walt Disney Studios Motion Pictures,False,marvel
25,26,Thor: The Dark World,"$206,362,140",3841,"$85,737,841",3841,"Nov 8, 2013",Walt Disney Studios Motion Pictures,False,marvel
26,27,Black Widow,"$183,651,655",4275,"$80,366,312",4160,"Jul 9, 2021",Walt Disney Studios Motion Pictures,False,marvel
27,28,Thor,"$181,030,624",3963,"$65,723,338",3955,"May 6, 2011",Paramount Pictures,False,marvel
28,29,Ant-Man,"$180,202,163",3868,"$57,225,526",3856,"Jul 17, 2015",Walt Disney Studios Motion Pictures,False,marvel
29,30,Captain America: The First Avenger,"$176,654,505",3715,"$65,058,524",3715,"Jul 22, 2011",Paramount Pictures,False,marvel
30,31,Eternals,"$164,870,234",4090,"$71,297,219",4090,"Nov 5, 2021",Walt Disney Studios Motion Pictures,False,marvel
31,32,The Incredible Hulk,"$134,806,913",3508,"$55,414,050",3505,"Jun 13, 2008",Universal Pictures,False,marvel

In [19]:
livemarvel=livemarvel.reset_index()

In [20]:
livemarvel=livemarvel.drop(['index'], axis=1)
livemarvel

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False,live reimaginings
2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False,live reimaginings
5,6,Maleficent,"$241,410,378",3948,"$69,431,298",3948,"May 30, 2014",Walt Disney Studios Motion Pictures,False,live reimaginings
6,7,Oz the Great and Powerful,"$234,911,825",3912,"$79,110,453",3912,"Mar 8, 2013",Walt Disney Studios Motion Pictures,False,live reimaginings
7,8,Cinderella,"$201,151,353",3848,"$67,877,361",3845,"Mar 13, 2015",Walt Disney Studios Motion Pictures,False,live reimaginings
8,9,101 Dalmatians,"$136,189,294",2901,"$33,504,025",2794,"Nov 27, 1996",Walt Disney Studios Motion Pictures,False,live reimaginings
9,10,Dumbo,"$114,766,307",4259,"$45,990,748",4259,"Mar 29, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
10,11,Maleficent: Mistress of Evil,"$113,929,605",3820,"$36,948,713",3790,"Oct 18, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
11,12,Cruella,"$86,103,234",3922,"$21,496,997",3892,"May 28, 2021",Walt Disney Studios Motion Pictures,False,live reimaginings
12,13,Alice Through the Looking Glass,"$77,041,381",3763,"$26,858,726",3763,"May 27, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
13,14,Pete's Dragon,"$76,233,151",3702,"$21,514,095",3702,"Aug 12, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
14,15,102 Dalmatians,"$66,957,026",2704,"$19,883,351",2704,"Nov 22, 2000",Walt Disney Studios Motion Pictures,False,live reimaginings
15,16,The Jungle Book,"$43,229,904",2012,"$5,129,959",1880,"Dec 25, 1994",Walt Disney Studios Motion Pictures,False,live reimaginings
16,17,Beauty and the Beast2020 Re-release,"$467,000",527,"$467,000",527,"Jul 17, 2020",Walt Disney Pictures,True,live reimaginings
17,1,Avengers: Endgame,"$858,373,000",4662,"$357,115,007",4662,"Apr 26, 2019",Walt Disney Studios Motion Pictures,False,marvel
18,2,Spider-Man: No Way Home,"$804,793,477",4336,"$260,138,569",4336,"Dec 17, 2021",Sony Pictures Entertainment (SPE),False,marvel
19,3,Black Panther,"$700,059,566",4084,"$202,003,951",4020,"Feb 16, 2018",Walt Disney Studios Motion Pictures,False,marvel
20,4,Avengers: Infinity War,"$678,815,482",4474,"$257,698,183",4474,"Apr 27, 2018",Walt Disney Studios Motion Pictures,False,marvel
21,5,The Avengers,"$623,357,910",4349,"$207,438,708",4349,"May 4, 2012",Walt Disney Studios Motion Pictures,False,marvel
22,6,Avengers: Age of Ultron,"$459,005,868",4276,"$191,271,109",4276,"May 1, 2015",Walt Disney Studios Motion Pictures,False,marvel
23,7,Black Panther: Wakanda Forever,"$453,829,060",4396,"$181,339,761",4396,"Nov 11, 2022",Walt Disney Studios Motion Pictures,False,marvel
24,8,Captain Marvel,"$426,829,839",4310,"$153,433,423",4310,"Mar 8, 2019",Walt Disney Studios Motion Pictures,False,marvel
25,9,Doctor Strange in the Multiverse of Madness,"$411,331,607",4534,"$187,420,998",4534,"May 6, 2022",Walt Disney Studios Motion Pictures,False,marvel
26,10,Iron Man 3,"$409,013,994",4253,"$174,144,585",4253,"May 3, 2013",Walt Disney Studios Motion Pictures,False,marvel
27,11,Captain America: Civil War,"$408,084,349",4226,"$179,139,142",4226,"May 6, 2016",Walt Disney Studios Motion Pictures,False,marvel
28,12,Spider-Man: Far from Home,"$390,532,085",4634,"$92,579,212",4634,"Jul 2, 2019",Sony Pictures Entertainment (SPE),False,marvel
29,13,Guardians of the Galaxy Vol. 2,"$389,813,101",4347,"$146,510,104",4347,"May 5, 2017",Walt Disney Studios Motion Pictures,False,marvel
30,14,Guardians of the Galaxy Vol. 3,"$356,577,614",4450,"$118,414,021",4450,"May 5, 2023",Walt Disney Studios Motion Pictures,False,marvel
31,15,Thor: Love and Thunder,"$343,256,830",4375,"$144,165,107",4375,"Jul 8, 2022",Walt Disney Studios Motion Pictures,False,marvel
32,16,Spider-Man: Homecoming,"$334,201,140",4348,"$117,027,503",4348,"Jul 7, 2017",Sony Pictures Entertainment (SPE),False,marvel
33,17,Guardians of the Galaxy,"$333,176,600",4088,"$94,320,883",4080,"Aug 1, 2014",Walt Disney Studios Motion Pictures,False,marvel
34,18,Iron Man,"$318,604,126",4154,"$98,618,668",4105,"May 2, 2008",Paramount Pictures,False,marvel
35,19,Thor: Ragnarok,"$315,058,289",4080,"$122,744,989",4080,"Nov 3, 2017",Walt Disney Studios Motion Pictures,False,marvel
36,20,Iron Man 2,"$312,433,331",4390,"$128,122,480",4380,"May 7, 2010",Paramount Pictures,False,marvel
37,21,Captain America: The Winter Soldier,"$259,766,572",3938,"$95,023,721",3938,"Apr 4, 2014",Walt Disney Studios Motion Pictures,False,marvel
38,22,Doctor Strange,"$232,641,920",3882,"$85,058,311",3882,"Nov 4, 2016",Walt Disney Studios Motion Pictures,False,marvel
39,23,Shang-Chi and the Legend of the Ten Rings,"$224,543,292",4300,"$75,388,688",4300,"Sep 3, 2021",Walt Disney Studios Motion Pictures,False,marvel
40,24,Ant-Man and the Wasp,"$216,648,740",4206,"$75,812,205",4206,"Jul 6, 2018",Walt Disney Studios Motion Pictures,False,marvel
41,25,Ant-Man and the Wasp: Quantumania,"$214,504,909",4345,"$106,109,650",4345,"Feb 17, 2023",Walt Disney Studios Motion Pictures,False,marvel
42,26,Thor: The Dark World,"$206,362,140",3841,"$85,737,841",3841,"Nov 8, 2013",Walt Disney Studios Motion Pictures,False,marvel
43,27,Black Widow,"$183,651,655",4275,"$80,366,312",4160,"Jul 9, 2021",Walt Disney Studios Motion Pictures,False,marvel
44,28,Thor,"$181,030,624",3963,"$65,723,338",3955,"May 6, 2011",Paramount Pictures,False,marvel
45,29,Ant-Man,"$180,202,163",3868,"$57,225,526",3856,"Jul 17, 2015",Walt Disney Studios Motion Pictures,False,marvel
46,30,Captain America: The First Avenger,"$176,654,505",3715,"$65,058,524",3715,"Jul 22, 2011",Paramount Pictures,False,marvel
47,31,Eternals,"$164,870,234",4090,"$71,297,219",4090,"Nov 5, 2021",Walt Disney Studios Motion Pictures,False,marvel
48,32,The Incredible Hulk,"$134,806,913",3508,"$55,414,050",3505,"Jun 13, 2008",Universal Pictures,False,marvel

In [21]:
disneypixar

,Unnamed: 0,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,0,1,Incredibles 2,"$608,581,744",4410,"$182,687,905",4410,"Jun 15, 2018",Walt Disney Studios Motion Pictures,False
1,1,2,Finding Dory,"$486,295,561",4305,"$135,060,273",4305,"Jun 17, 2016",Walt Disney Studios Motion Pictures,False
2,2,3,Toy Story 4,"$434,038,008",4575,"$120,908,065",4575,"Jun 21, 2019",Walt Disney Studios Motion Pictures,False
3,3,4,Toy Story 3,"$415,004,880",4028,"$110,307,189",4028,"Jun 18, 2010",Walt Disney Studios Motion Pictures,False
4,4,5,Inside Out,"$356,461,711",4158,"$90,440,272",3946,"Jun 19, 2015",Walt Disney Studios Motion Pictures,False
5,5,6,Finding Nemo,"$339,714,978",3425,"$70,251,710",3374,"May 30, 2003",Walt Disney Studios Motion Pictures,False
6,6,7,Up,"$293,004,164",3886,"$68,108,790",3766,"May 29, 2009",Walt Disney Studios Motion Pictures,False
7,7,8,Monsters University,"$268,492,764",4004,"$82,429,469",4004,"Jun 21, 2013",Walt Disney Studios Motion Pictures,False
8,8,9,The Incredibles,"$261,441,092",3933,"$70,467,623",3933,"Nov 5, 2004",Walt Disney Studios Motion Pictures,False
9,9,10,"Monsters, Inc.","$255,873,250",3649,"$62,577,067",3237,"Nov 2, 2001",Walt Disney Studios Motion Pictures,False
10,10,11,Toy Story 2,"$245,852,179",3257,"$300,163",1,"Nov 19, 1999",Walt Disney Studios Motion Pictures,False
11,11,12,Cars,"$244,082,982",3988,"$60,119,509",3985,"Jun 9, 2006",Walt Disney Studios Motion Pictures,False
12,12,13,Brave,"$237,283,207",4164,"$66,323,594",4164,"Jun 22, 2012",Walt Disney Studios Motion Pictures,False
13,13,14,WALL·E,"$223,808,164",3992,"$63,087,526",3992,"Jun 27, 2008",Walt Disney Studios Motion Pictures,False
14,14,15,Coco,"$210,460,015",3987,"$50,802,605",3987,"Nov 22, 2017",Walt Disney Studios Motion Pictures,False
15,15,16,Ratatouille,"$206,445,654",3940,"$47,027,395",3940,"Jun 29, 2007",Walt Disney Studios Motion Pictures,False
16,16,17,Toy Story,"$191,796,233",2574,"$29,140,617",2457,"Nov 22, 1995",Walt Disney Studios Motion Pictures,False
17,17,18,Cars 2,"$191,452,396",4115,"$66,135,507",4115,"Jun 24, 2011",Walt Disney Studios Motion Pictures,False
18,18,19,A Bug's Life,"$162,798,565",2773,"$291,121",1,"Nov 20, 1998",Walt Disney Studios Motion Pictures,False
19,19,20,Cars 3,"$152,901,115",4256,"$53,688,680",4256,"Jun 16, 2017",Walt Disney Studios Motion Pictures,False
20,20,21,The Good Dinosaur,"$123,087,120",3749,"$39,155,217",3749,"Nov 25, 2015",Walt Disney Studios Motion Pictures,False
21,21,22,Onward,"$61,555,145",4310,"$39,119,861",4310,"Mar 6, 2020",Walt Disney Studios Motion Pictures,False
22,22,23,Finding Nemo2012 3D Release,"$41,128,283",2904,"$16,687,773",2904,"Sep 14, 2012",Walt Disney Studios Motion Pictures,False
23,23,24,"Monsters, Inc.2012 3D Release","$34,043,006",2618,"$4,774,686",2618,"Dec 19, 2012",Walt Disney Studios Motion Pictures,False
24,24,25,Toy Story2009 Re-release,"$30,702,446",1752,"$12,491,789",1745,"Oct 2, 2009",Walt Disney Studios Motion Pictures,False
25,25,26,Toy Story2020 Re-release,"$727,000",2102,"$505,000",2102,"Nov 6, 2020",Walt Disney Studios Motion Pictures,True
26,26,27,"Monsters, Inc.2020 Re-release","$726,000",1875,"$494,000",1875,"Oct 23, 2020",Walt Disney Studios Motion Pictures,True
27,27,28,Inside Out2020 Re-release,"$460,000",442,"$340,000",442,"Jul 10, 2020",Walt Disney Pictures,True

In [22]:
disneypixar=disneypixar.drop(['Unnamed: 0'], axis=1)
disneypixar

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Incredibles 2,"$608,581,744",4410,"$182,687,905",4410,"Jun 15, 2018",Walt Disney Studios Motion Pictures,False
1,2,Finding Dory,"$486,295,561",4305,"$135,060,273",4305,"Jun 17, 2016",Walt Disney Studios Motion Pictures,False
2,3,Toy Story 4,"$434,038,008",4575,"$120,908,065",4575,"Jun 21, 2019",Walt Disney Studios Motion Pictures,False
3,4,Toy Story 3,"$415,004,880",4028,"$110,307,189",4028,"Jun 18, 2010",Walt Disney Studios Motion Pictures,False
4,5,Inside Out,"$356,461,711",4158,"$90,440,272",3946,"Jun 19, 2015",Walt Disney Studios Motion Pictures,False
5,6,Finding Nemo,"$339,714,978",3425,"$70,251,710",3374,"May 30, 2003",Walt Disney Studios Motion Pictures,False
6,7,Up,"$293,004,164",3886,"$68,108,790",3766,"May 29, 2009",Walt Disney Studios Motion Pictures,False
7,8,Monsters University,"$268,492,764",4004,"$82,429,469",4004,"Jun 21, 2013",Walt Disney Studios Motion Pictures,False
8,9,The Incredibles,"$261,441,092",3933,"$70,467,623",3933,"Nov 5, 2004",Walt Disney Studios Motion Pictures,False
9,10,"Monsters, Inc.","$255,873,250",3649,"$62,577,067",3237,"Nov 2, 2001",Walt Disney Studios Motion Pictures,False
10,11,Toy Story 2,"$245,852,179",3257,"$300,163",1,"Nov 19, 1999",Walt Disney Studios Motion Pictures,False
11,12,Cars,"$244,082,982",3988,"$60,119,509",3985,"Jun 9, 2006",Walt Disney Studios Motion Pictures,False
12,13,Brave,"$237,283,207",4164,"$66,323,594",4164,"Jun 22, 2012",Walt Disney Studios Motion Pictures,False
13,14,WALL·E,"$223,808,164",3992,"$63,087,526",3992,"Jun 27, 2008",Walt Disney Studios Motion Pictures,False
14,15,Coco,"$210,460,015",3987,"$50,802,605",3987,"Nov 22, 2017",Walt Disney Studios Motion Pictures,False
15,16,Ratatouille,"$206,445,654",3940,"$47,027,395",3940,"Jun 29, 2007",Walt Disney Studios Motion Pictures,False
16,17,Toy Story,"$191,796,233",2574,"$29,140,617",2457,"Nov 22, 1995",Walt Disney Studios Motion Pictures,False
17,18,Cars 2,"$191,452,396",4115,"$66,135,507",4115,"Jun 24, 2011",Walt Disney Studios Motion Pictures,False
18,19,A Bug's Life,"$162,798,565",2773,"$291,121",1,"Nov 20, 1998",Walt Disney Studios Motion Pictures,False
19,20,Cars 3,"$152,901,115",4256,"$53,688,680",4256,"Jun 16, 2017",Walt Disney Studios Motion Pictures,False
20,21,The Good Dinosaur,"$123,087,120",3749,"$39,155,217",3749,"Nov 25, 2015",Walt Disney Studios Motion Pictures,False
21,22,Onward,"$61,555,145",4310,"$39,119,861",4310,"Mar 6, 2020",Walt Disney Studios Motion Pictures,False
22,23,Finding Nemo2012 3D Release,"$41,128,283",2904,"$16,687,773",2904,"Sep 14, 2012",Walt Disney Studios Motion Pictures,False
23,24,"Monsters, Inc.2012 3D Release","$34,043,006",2618,"$4,774,686",2618,"Dec 19, 2012",Walt Disney Studios Motion Pictures,False
24,25,Toy Story2009 Re-release,"$30,702,446",1752,"$12,491,789",1745,"Oct 2, 2009",Walt Disney Studios Motion Pictures,False
25,26,Toy Story2020 Re-release,"$727,000",2102,"$505,000",2102,"Nov 6, 2020",Walt Disney Studios Motion Pictures,True
26,27,"Monsters, Inc.2020 Re-release","$726,000",1875,"$494,000",1875,"Oct 23, 2020",Walt Disney Studios Motion Pictures,True
27,28,Inside Out2020 Re-release,"$460,000",442,"$340,000",442,"Jul 10, 2020",Walt Disney Pictures,True

In [23]:
disneypixar=disneypixar.drop(disneypixar.index[22:])
disneypixar

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Incredibles 2,"$608,581,744",4410,"$182,687,905",4410,"Jun 15, 2018",Walt Disney Studios Motion Pictures,False
1,2,Finding Dory,"$486,295,561",4305,"$135,060,273",4305,"Jun 17, 2016",Walt Disney Studios Motion Pictures,False
2,3,Toy Story 4,"$434,038,008",4575,"$120,908,065",4575,"Jun 21, 2019",Walt Disney Studios Motion Pictures,False
3,4,Toy Story 3,"$415,004,880",4028,"$110,307,189",4028,"Jun 18, 2010",Walt Disney Studios Motion Pictures,False
4,5,Inside Out,"$356,461,711",4158,"$90,440,272",3946,"Jun 19, 2015",Walt Disney Studios Motion Pictures,False
5,6,Finding Nemo,"$339,714,978",3425,"$70,251,710",3374,"May 30, 2003",Walt Disney Studios Motion Pictures,False
6,7,Up,"$293,004,164",3886,"$68,108,790",3766,"May 29, 2009",Walt Disney Studios Motion Pictures,False
7,8,Monsters University,"$268,492,764",4004,"$82,429,469",4004,"Jun 21, 2013",Walt Disney Studios Motion Pictures,False
8,9,The Incredibles,"$261,441,092",3933,"$70,467,623",3933,"Nov 5, 2004",Walt Disney Studios Motion Pictures,False
9,10,"Monsters, Inc.","$255,873,250",3649,"$62,577,067",3237,"Nov 2, 2001",Walt Disney Studios Motion Pictures,False
10,11,Toy Story 2,"$245,852,179",3257,"$300,163",1,"Nov 19, 1999",Walt Disney Studios Motion Pictures,False
11,12,Cars,"$244,082,982",3988,"$60,119,509",3985,"Jun 9, 2006",Walt Disney Studios Motion Pictures,False
12,13,Brave,"$237,283,207",4164,"$66,323,594",4164,"Jun 22, 2012",Walt Disney Studios Motion Pictures,False
13,14,WALL·E,"$223,808,164",3992,"$63,087,526",3992,"Jun 27, 2008",Walt Disney Studios Motion Pictures,False
14,15,Coco,"$210,460,015",3987,"$50,802,605",3987,"Nov 22, 2017",Walt Disney Studios Motion Pictures,False
15,16,Ratatouille,"$206,445,654",3940,"$47,027,395",3940,"Jun 29, 2007",Walt Disney Studios Motion Pictures,False
16,17,Toy Story,"$191,796,233",2574,"$29,140,617",2457,"Nov 22, 1995",Walt Disney Studios Motion Pictures,False
17,18,Cars 2,"$191,452,396",4115,"$66,135,507",4115,"Jun 24, 2011",Walt Disney Studios Motion Pictures,False
18,19,A Bug's Life,"$162,798,565",2773,"$291,121",1,"Nov 20, 1998",Walt Disney Studios Motion Pictures,False
19,20,Cars 3,"$152,901,115",4256,"$53,688,680",4256,"Jun 16, 2017",Walt Disney Studios Motion Pictures,False
20,21,The Good Dinosaur,"$123,087,120",3749,"$39,155,217",3749,"Nov 25, 2015",Walt Disney Studios Motion Pictures,False
21,22,Onward,"$61,555,145",4310,"$39,119,861",4310,"Mar 6, 2020",Walt Disney Studios Motion Pictures,False

In [24]:
disneypixar['category'] = 'pixar'
disneypixar

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,Incredibles 2,"$608,581,744",4410,"$182,687,905",4410,"Jun 15, 2018",Walt Disney Studios Motion Pictures,False,pixar
1,2,Finding Dory,"$486,295,561",4305,"$135,060,273",4305,"Jun 17, 2016",Walt Disney Studios Motion Pictures,False,pixar
2,3,Toy Story 4,"$434,038,008",4575,"$120,908,065",4575,"Jun 21, 2019",Walt Disney Studios Motion Pictures,False,pixar
3,4,Toy Story 3,"$415,004,880",4028,"$110,307,189",4028,"Jun 18, 2010",Walt Disney Studios Motion Pictures,False,pixar
4,5,Inside Out,"$356,461,711",4158,"$90,440,272",3946,"Jun 19, 2015",Walt Disney Studios Motion Pictures,False,pixar
5,6,Finding Nemo,"$339,714,978",3425,"$70,251,710",3374,"May 30, 2003",Walt Disney Studios Motion Pictures,False,pixar
6,7,Up,"$293,004,164",3886,"$68,108,790",3766,"May 29, 2009",Walt Disney Studios Motion Pictures,False,pixar
7,8,Monsters University,"$268,492,764",4004,"$82,429,469",4004,"Jun 21, 2013",Walt Disney Studios Motion Pictures,False,pixar
8,9,The Incredibles,"$261,441,092",3933,"$70,467,623",3933,"Nov 5, 2004",Walt Disney Studios Motion Pictures,False,pixar
9,10,"Monsters, Inc.","$255,873,250",3649,"$62,577,067",3237,"Nov 2, 2001",Walt Disney Studios Motion Pictures,False,pixar
10,11,Toy Story 2,"$245,852,179",3257,"$300,163",1,"Nov 19, 1999",Walt Disney Studios Motion Pictures,False,pixar
11,12,Cars,"$244,082,982",3988,"$60,119,509",3985,"Jun 9, 2006",Walt Disney Studios Motion Pictures,False,pixar
12,13,Brave,"$237,283,207",4164,"$66,323,594",4164,"Jun 22, 2012",Walt Disney Studios Motion Pictures,False,pixar
13,14,WALL·E,"$223,808,164",3992,"$63,087,526",3992,"Jun 27, 2008",Walt Disney Studios Motion Pictures,False,pixar
14,15,Coco,"$210,460,015",3987,"$50,802,605",3987,"Nov 22, 2017",Walt Disney Studios Motion Pictures,False,pixar
15,16,Ratatouille,"$206,445,654",3940,"$47,027,395",3940,"Jun 29, 2007",Walt Disney Studios Motion Pictures,False,pixar
16,17,Toy Story,"$191,796,233",2574,"$29,140,617",2457,"Nov 22, 1995",Walt Disney Studios Motion Pictures,False,pixar
17,18,Cars 2,"$191,452,396",4115,"$66,135,507",4115,"Jun 24, 2011",Walt Disney Studios Motion Pictures,False,pixar
18,19,A Bug's Life,"$162,798,565",2773,"$291,121",1,"Nov 20, 1998",Walt Disney Studios Motion Pictures,False,pixar
19,20,Cars 3,"$152,901,115",4256,"$53,688,680",4256,"Jun 16, 2017",Walt Disney Studios Motion Pictures,False,pixar
20,21,The Good Dinosaur,"$123,087,120",3749,"$39,155,217",3749,"Nov 25, 2015",Walt Disney Studios Motion Pictures,False,pixar
21,22,Onward,"$61,555,145",4310,"$39,119,861",4310,"Mar 6, 2020",Walt Disney Studios Motion Pictures,False,pixar

In [25]:
livemarvelpixar = pd.concat([livemarvel, disneypixar])
livemarvelpixar

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False,live reimaginings
2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False,live reimaginings
...,...,...,...,...,...,...,...,...,...,...
17,18,Cars 2,"$191,452,396",4115,"$66,135,507",4115,"Jun 24, 2011",Walt Disney Studios Motion Pictures,False,pixar
18,19,A Bug's Life,"$162,798,565",2773,"$291,121",1,"Nov 20, 1998",Walt Disney Studios Motion Pictures,False,pixar
19,20,Cars 3,"$152,901,115",4256,"$53,688,680",4256,"Jun 16, 2017",Walt Disney Studios Motion Pictures,False,pixar
20,21,The Good Dinosaur,"$123,087,120",3749,"$39,155,217",3749,"Nov 25, 2015",Walt Disney Studios Motion Pictures,False,pixar
21,22,Onward,"$61,555,145",4310,"$39,119,861",4310,"Mar 6, 2020",Walt Disney Studios Motion Pictures,False,pixar

In [26]:
livemarvelpixar=livemarvelpixar.reset_index()

In [27]:
livemarvelpixar=livemarvelpixar.drop(['index'], axis=1)
livemarvelpixar

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False,live reimaginings
2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False,live reimaginings
...,...,...,...,...,...,...,...,...,...,...
66,18,Cars 2,"$191,452,396",4115,"$66,135,507",4115,"Jun 24, 2011",Walt Disney Studios Motion Pictures,False,pixar
67,19,A Bug's Life,"$162,798,565",2773,"$291,121",1,"Nov 20, 1998",Walt Disney Studios Motion Pictures,False,pixar
68,20,Cars 3,"$152,901,115",4256,"$53,688,680",4256,"Jun 16, 2017",Walt Disney Studios Motion Pictures,False,pixar
69,21,The Good Dinosaur,"$123,087,120",3749,"$39,155,217",3749,"Nov 25, 2015",Walt Disney Studios Motion Pictures,False,pixar
70,22,Onward,"$61,555,145",4310,"$39,119,861",4310,"Mar 6, 2020",Walt Disney Studios Motion Pictures,False,pixar

In [28]:
disneyspiderman

,Unnamed: 0,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,0,1,Spider-Man: No Way Home,"$804,793,477",4336,"$260,138,569",4336,"Dec 17, 2021",Sony Pictures Entertainment (SPE),False
1,1,2,Spider-Man,"$403,706,375",3876,"$114,844,116",3615,"May 3, 2002",Sony Pictures Entertainment (SPE),False
2,2,3,Spider-Man: Far from Home,"$390,532,085",4634,"$92,579,212",4634,"Jul 2, 2019",Sony Pictures Entertainment (SPE),False
3,3,4,Spider-Man 2,"$373,585,825",4166,"$88,156,227",4152,"Jun 30, 2004",Sony Pictures Entertainment (SPE),False
4,4,5,Spider-Man 3,"$336,530,303",4324,"$151,116,516",4252,"May 4, 2007",Sony Pictures Entertainment (SPE),False
5,5,6,Spider-Man: Homecoming,"$334,201,140",4348,"$117,027,503",4348,"Jul 7, 2017",Sony Pictures Entertainment (SPE),False
6,6,7,The Amazing Spider-Man,"$262,030,663",4318,"$62,004,688",4318,"Jul 3, 2012",Sony Pictures Entertainment (SPE),False
7,7,8,The Amazing Spider-Man 2,"$202,853,933",4324,"$91,608,337",4324,"May 2, 2014",Sony Pictures Entertainment (SPE),False
8,8,9,Spider-Man: Into the Spider-Verse,"$190,241,310",3813,"$35,363,376",3813,"Dec 14, 2018",Sony Pictures Entertainment (SPE),False
9,9,10,Spider-Man: No Way Home2022 Re-release,"$9,321,593",3935,"$5,403,230",3935,"Sep 2, 2022",Sony Pictures Entertainment (SPE),False
10,10,11,Spider-Man/Men in Black IIDouble Bill,"$6,632,970",2078,"$2,111,862",2078,"Sep 6, 2002",Sony Pictures Entertainment (SPE),False

In [29]:
disneyspiderman=disneyspiderman.drop(['Unnamed: 0'], axis=1)
disneyspiderman

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Spider-Man: No Way Home,"$804,793,477",4336,"$260,138,569",4336,"Dec 17, 2021",Sony Pictures Entertainment (SPE),False
1,2,Spider-Man,"$403,706,375",3876,"$114,844,116",3615,"May 3, 2002",Sony Pictures Entertainment (SPE),False
2,3,Spider-Man: Far from Home,"$390,532,085",4634,"$92,579,212",4634,"Jul 2, 2019",Sony Pictures Entertainment (SPE),False
3,4,Spider-Man 2,"$373,585,825",4166,"$88,156,227",4152,"Jun 30, 2004",Sony Pictures Entertainment (SPE),False
4,5,Spider-Man 3,"$336,530,303",4324,"$151,116,516",4252,"May 4, 2007",Sony Pictures Entertainment (SPE),False
5,6,Spider-Man: Homecoming,"$334,201,140",4348,"$117,027,503",4348,"Jul 7, 2017",Sony Pictures Entertainment (SPE),False
6,7,The Amazing Spider-Man,"$262,030,663",4318,"$62,004,688",4318,"Jul 3, 2012",Sony Pictures Entertainment (SPE),False
7,8,The Amazing Spider-Man 2,"$202,853,933",4324,"$91,608,337",4324,"May 2, 2014",Sony Pictures Entertainment (SPE),False
8,9,Spider-Man: Into the Spider-Verse,"$190,241,310",3813,"$35,363,376",3813,"Dec 14, 2018",Sony Pictures Entertainment (SPE),False
9,10,Spider-Man: No Way Home2022 Re-release,"$9,321,593",3935,"$5,403,230",3935,"Sep 2, 2022",Sony Pictures Entertainment (SPE),False
10,11,Spider-Man/Men in Black IIDouble Bill,"$6,632,970",2078,"$2,111,862",2078,"Sep 6, 2002",Sony Pictures Entertainment (SPE),False

In [30]:
disneyspiderman=disneyspiderman.drop(disneyspiderman.index[9:])
disneyspiderman

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Spider-Man: No Way Home,"$804,793,477",4336,"$260,138,569",4336,"Dec 17, 2021",Sony Pictures Entertainment (SPE),False
1,2,Spider-Man,"$403,706,375",3876,"$114,844,116",3615,"May 3, 2002",Sony Pictures Entertainment (SPE),False
2,3,Spider-Man: Far from Home,"$390,532,085",4634,"$92,579,212",4634,"Jul 2, 2019",Sony Pictures Entertainment (SPE),False
3,4,Spider-Man 2,"$373,585,825",4166,"$88,156,227",4152,"Jun 30, 2004",Sony Pictures Entertainment (SPE),False
4,5,Spider-Man 3,"$336,530,303",4324,"$151,116,516",4252,"May 4, 2007",Sony Pictures Entertainment (SPE),False
5,6,Spider-Man: Homecoming,"$334,201,140",4348,"$117,027,503",4348,"Jul 7, 2017",Sony Pictures Entertainment (SPE),False
6,7,The Amazing Spider-Man,"$262,030,663",4318,"$62,004,688",4318,"Jul 3, 2012",Sony Pictures Entertainment (SPE),False
7,8,The Amazing Spider-Man 2,"$202,853,933",4324,"$91,608,337",4324,"May 2, 2014",Sony Pictures Entertainment (SPE),False
8,9,Spider-Man: Into the Spider-Verse,"$190,241,310",3813,"$35,363,376",3813,"Dec 14, 2018",Sony Pictures Entertainment (SPE),False

In [31]:
disneyspiderman['category'] = 'spiderman'
disneyspiderman

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,Spider-Man: No Way Home,"$804,793,477",4336,"$260,138,569",4336,"Dec 17, 2021",Sony Pictures Entertainment (SPE),False,spiderman
1,2,Spider-Man,"$403,706,375",3876,"$114,844,116",3615,"May 3, 2002",Sony Pictures Entertainment (SPE),False,spiderman
2,3,Spider-Man: Far from Home,"$390,532,085",4634,"$92,579,212",4634,"Jul 2, 2019",Sony Pictures Entertainment (SPE),False,spiderman
3,4,Spider-Man 2,"$373,585,825",4166,"$88,156,227",4152,"Jun 30, 2004",Sony Pictures Entertainment (SPE),False,spiderman
4,5,Spider-Man 3,"$336,530,303",4324,"$151,116,516",4252,"May 4, 2007",Sony Pictures Entertainment (SPE),False,spiderman
5,6,Spider-Man: Homecoming,"$334,201,140",4348,"$117,027,503",4348,"Jul 7, 2017",Sony Pictures Entertainment (SPE),False,spiderman
6,7,The Amazing Spider-Man,"$262,030,663",4318,"$62,004,688",4318,"Jul 3, 2012",Sony Pictures Entertainment (SPE),False,spiderman
7,8,The Amazing Spider-Man 2,"$202,853,933",4324,"$91,608,337",4324,"May 2, 2014",Sony Pictures Entertainment (SPE),False,spiderman
8,9,Spider-Man: Into the Spider-Verse,"$190,241,310",3813,"$35,363,376",3813,"Dec 14, 2018",Sony Pictures Entertainment (SPE),False,spiderman

In [32]:
lmps = pd.concat([livemarvelpixar, disneyspiderman])
lmps

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False,live reimaginings
2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False,live reimaginings
...,...,...,...,...,...,...,...,...,...,...
4,5,Spider-Man 3,"$336,530,303",4324,"$151,116,516",4252,"May 4, 2007",Sony Pictures Entertainment (SPE),False,spiderman
5,6,Spider-Man: Homecoming,"$334,201,140",4348,"$117,027,503",4348,"Jul 7, 2017",Sony Pictures Entertainment (SPE),False,spiderman
6,7,The Amazing Spider-Man,"$262,030,663",4318,"$62,004,688",4318,"Jul 3, 2012",Sony Pictures Entertainment (SPE),False,spiderman
7,8,The Amazing Spider-Man 2,"$202,853,933",4324,"$91,608,337",4324,"May 2, 2014",Sony Pictures Entertainment (SPE),False,spiderman
8,9,Spider-Man: Into the Spider-Verse,"$190,241,310",3813,"$35,363,376",3813,"Dec 14, 2018",Sony Pictures Entertainment (SPE),False,spiderman

In [33]:
lmps=lmps.reset_index()

In [34]:
lmps=lmps.drop(['index'], axis=1)
lmps

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False,live reimaginings
2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False,live reimaginings
...,...,...,...,...,...,...,...,...,...,...
75,5,Spider-Man 3,"$336,530,303",4324,"$151,116,516",4252,"May 4, 2007",Sony Pictures Entertainment (SPE),False,spiderman
76,6,Spider-Man: Homecoming,"$334,201,140",4348,"$117,027,503",4348,"Jul 7, 2017",Sony Pictures Entertainment (SPE),False,spiderman
77,7,The Amazing Spider-Man,"$262,030,663",4318,"$62,004,688",4318,"Jul 3, 2012",Sony Pictures Entertainment (SPE),False,spiderman
78,8,The Amazing Spider-Man 2,"$202,853,933",4324,"$91,608,337",4324,"May 2, 2014",Sony Pictures Entertainment (SPE),False,spiderman
79,9,Spider-Man: Into the Spider-Verse,"$190,241,310",3813,"$35,363,376",3813,"Dec 14, 2018",Sony Pictures Entertainment (SPE),False,spiderman

In [35]:
disneystarwars

,Unnamed: 0,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,0,1,Star Wars: Episode VII - The Force Awakens,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,False
1,1,2,Star Wars: Episode VIII - The Last Jedi,"$620,181,382",4232,"$220,009,584",4232,"Dec 15, 2017",Walt Disney Studios Motion Pictures,False
2,2,3,Rogue One: A Star Wars Story,"$532,177,324",4157,"$155,081,681",4157,"Dec 16, 2016",Walt Disney Studios Motion Pictures,False
3,3,4,Star Wars: Episode IX - The Rise of Skywalker,"$515,202,542",4406,"$177,383,864",4406,"Dec 20, 2019",Walt Disney Studios Motion Pictures,False
4,4,5,Star Wars: Episode I - The Phantom Menace,"$431,088,295",3126,"$64,820,970",2970,"May 19, 1999",Twentieth Century Fox,False
5,5,6,Star Wars: Episode III - Revenge of the Sith,"$380,270,577",3663,"$108,435,841",3661,"May 19, 2005",Twentieth Century Fox,False
6,6,7,Star Wars: Episode IV - A New Hope,"$307,263,857",1750,"$1,554,475",43,"May 25, 1977",Twentieth Century Fox,False
7,7,8,Star Wars: Episode II - Attack of the Clones,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False
8,8,9,Star Wars: Episode VI - Return of the Jedi,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False
9,9,10,Solo: A Star Wars Story,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,False
10,10,11,Star Wars: Episode V - The Empire Strikes Back,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False
11,11,12,Star Wars: Episode IV - A New Hope1997 Special...,"$138,257,865",2375,"$35,906,661",2104,"Jan 31, 1997",Twentieth Century Fox,False
12,12,13,Star Wars: Episode V - The Empire Strikes Back...,"$67,597,694",2322,"$21,975,993",2111,"Feb 21, 1997",Twentieth Century Fox,False
13,13,14,Star Wars: Episode VI - Return of the Jedi1997...,"$45,470,437",2111,"$16,293,531",2111,"Mar 14, 1997",Twentieth Century Fox,False
14,14,15,Star Wars: Episode I - The Phantom Menace2012 ...,"$43,456,382",2655,"$22,469,932",2655,"Feb 10, 2012",Twentieth Century Fox,False
15,15,16,Star Wars: The Clone Wars,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False
16,16,17,Star Wars: Episode IV - A New Hope1982 Re-release,"$15,476,785",1070,"$3,766,803",1070,"Aug 13, 1982",Twentieth Century Fox,False
17,17,18,Star Wars: Episode V - The Empire Strikes Back...,"$13,276,241",1006,"$3,949,478",992,"Nov 19, 1982",Twentieth Century Fox,False
18,18,19,Star Wars: Episode VI - Return of the Jedi1985...,"$11,252,123",894,"$3,209,056",849,"Mar 29, 1985",Twentieth Century Fox,False
19,19,20,Star Wars: Episode II - Attack of the Clones20...,"$8,485,488",58,"$1,435,259",58,"Nov 1, 2002",Twentieth Century Fox,False
20,20,21,Star Wars: Episode VI - Return of the Jedi2023...,"$7,259,924",475,"$5,100,654",475,"Apr 28, 2023",NaN,False
21,21,22,Star Wars: Episode V - The Empire Strikes Back...,"$2,482,000",2097,"$611,000",611,"Jul 10, 2020",Walt Disney Studios Motion Pictures,True
22,22,23,Rogue One: A Star Wars Story2022 Re-release,"$1,362,667",255,"$1,060,459",255,"Aug 26, 2022",Walt Disney Studios Motion Pictures,False
23,23,-,Untitled Taika Waititi Star Wars Film,-,-,-,-,"May 22, 2026",Walt Disney Pictures,False
24,24,-,Star Wars: New Jedi Order,-,-,-,-,"Dec 17, 2027",Walt Disney Pictures,False

In [36]:
disneystarwars=disneystarwars.drop(['Unnamed: 0'], axis=1)
disneystarwars

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Star Wars: Episode VII - The Force Awakens,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,False
1,2,Star Wars: Episode VIII - The Last Jedi,"$620,181,382",4232,"$220,009,584",4232,"Dec 15, 2017",Walt Disney Studios Motion Pictures,False
2,3,Rogue One: A Star Wars Story,"$532,177,324",4157,"$155,081,681",4157,"Dec 16, 2016",Walt Disney Studios Motion Pictures,False
3,4,Star Wars: Episode IX - The Rise of Skywalker,"$515,202,542",4406,"$177,383,864",4406,"Dec 20, 2019",Walt Disney Studios Motion Pictures,False
4,5,Star Wars: Episode I - The Phantom Menace,"$431,088,295",3126,"$64,820,970",2970,"May 19, 1999",Twentieth Century Fox,False
5,6,Star Wars: Episode III - Revenge of the Sith,"$380,270,577",3663,"$108,435,841",3661,"May 19, 2005",Twentieth Century Fox,False
6,7,Star Wars: Episode IV - A New Hope,"$307,263,857",1750,"$1,554,475",43,"May 25, 1977",Twentieth Century Fox,False
7,8,Star Wars: Episode II - Attack of the Clones,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False
8,9,Star Wars: Episode VI - Return of the Jedi,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False
9,10,Solo: A Star Wars Story,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,False
10,11,Star Wars: Episode V - The Empire Strikes Back,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False
11,12,Star Wars: Episode IV - A New Hope1997 Special...,"$138,257,865",2375,"$35,906,661",2104,"Jan 31, 1997",Twentieth Century Fox,False
12,13,Star Wars: Episode V - The Empire Strikes Back...,"$67,597,694",2322,"$21,975,993",2111,"Feb 21, 1997",Twentieth Century Fox,False
13,14,Star Wars: Episode VI - Return of the Jedi1997...,"$45,470,437",2111,"$16,293,531",2111,"Mar 14, 1997",Twentieth Century Fox,False
14,15,Star Wars: Episode I - The Phantom Menace2012 ...,"$43,456,382",2655,"$22,469,932",2655,"Feb 10, 2012",Twentieth Century Fox,False
15,16,Star Wars: The Clone Wars,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False
16,17,Star Wars: Episode IV - A New Hope1982 Re-release,"$15,476,785",1070,"$3,766,803",1070,"Aug 13, 1982",Twentieth Century Fox,False
17,18,Star Wars: Episode V - The Empire Strikes Back...,"$13,276,241",1006,"$3,949,478",992,"Nov 19, 1982",Twentieth Century Fox,False
18,19,Star Wars: Episode VI - Return of the Jedi1985...,"$11,252,123",894,"$3,209,056",849,"Mar 29, 1985",Twentieth Century Fox,False
19,20,Star Wars: Episode II - Attack of the Clones20...,"$8,485,488",58,"$1,435,259",58,"Nov 1, 2002",Twentieth Century Fox,False
20,21,Star Wars: Episode VI - Return of the Jedi2023...,"$7,259,924",475,"$5,100,654",475,"Apr 28, 2023",NaN,False
21,22,Star Wars: Episode V - The Empire Strikes Back...,"$2,482,000",2097,"$611,000",611,"Jul 10, 2020",Walt Disney Studios Motion Pictures,True
22,23,Rogue One: A Star Wars Story2022 Re-release,"$1,362,667",255,"$1,060,459",255,"Aug 26, 2022",Walt Disney Studios Motion Pictures,False
23,-,Untitled Taika Waititi Star Wars Film,-,-,-,-,"May 22, 2026",Walt Disney Pictures,False
24,-,Star Wars: New Jedi Order,-,-,-,-,"Dec 17, 2027",Walt Disney Pictures,False

In [37]:
disneystarwars['Release']

0            Star Wars: Episode VII - The Force Awakens
1               Star Wars: Episode VIII - The Last Jedi
2                          Rogue One: A Star Wars Story
3         Star Wars: Episode IX - The Rise of Skywalker
4             Star Wars: Episode I - The Phantom Menace
5          Star Wars: Episode III - Revenge of the Sith
6                    Star Wars: Episode IV - A New Hope
7          Star Wars: Episode II - Attack of the Clones
8            Star Wars: Episode VI - Return of the Jedi
9                               Solo: A Star Wars Story
10       Star Wars: Episode V - The Empire Strikes Back
11    Star Wars: Episode IV - A New Hope1997 Special...
12    Star Wars: Episode V - The Empire Strikes Back...
13    Star Wars: Episode VI - Return of the Jedi1997...
14    Star Wars: Episode I - The Phantom Menace2012 ...
15                            Star Wars: The Clone Wars
16    Star Wars: Episode IV - A New Hope1982 Re-release
17    Star Wars: Episode V - The Empire Strikes Back...
18    Star Wars: Episode VI - Return of the Jedi1985...
19    Star Wars: Episode II - Attack of the Clones20...
20    Star Wars: Episode VI - Return of the Jedi2023...
21    Star Wars: Episode V - The Empire Strikes Back...
22          Rogue One: A Star Wars Story2022 Re-release
23                Untitled Taika Waititi Star Wars Film
24                            Star Wars: New Jedi Order
Name: Release, dtype: object

In [38]:
disneystarwars

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Star Wars: Episode VII - The Force Awakens,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,False
1,2,Star Wars: Episode VIII - The Last Jedi,"$620,181,382",4232,"$220,009,584",4232,"Dec 15, 2017",Walt Disney Studios Motion Pictures,False
2,3,Rogue One: A Star Wars Story,"$532,177,324",4157,"$155,081,681",4157,"Dec 16, 2016",Walt Disney Studios Motion Pictures,False
3,4,Star Wars: Episode IX - The Rise of Skywalker,"$515,202,542",4406,"$177,383,864",4406,"Dec 20, 2019",Walt Disney Studios Motion Pictures,False
4,5,Star Wars: Episode I - The Phantom Menace,"$431,088,295",3126,"$64,820,970",2970,"May 19, 1999",Twentieth Century Fox,False
5,6,Star Wars: Episode III - Revenge of the Sith,"$380,270,577",3663,"$108,435,841",3661,"May 19, 2005",Twentieth Century Fox,False
6,7,Star Wars: Episode IV - A New Hope,"$307,263,857",1750,"$1,554,475",43,"May 25, 1977",Twentieth Century Fox,False
7,8,Star Wars: Episode II - Attack of the Clones,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False
8,9,Star Wars: Episode VI - Return of the Jedi,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False
9,10,Solo: A Star Wars Story,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,False
10,11,Star Wars: Episode V - The Empire Strikes Back,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False
11,12,Star Wars: Episode IV - A New Hope1997 Special...,"$138,257,865",2375,"$35,906,661",2104,"Jan 31, 1997",Twentieth Century Fox,False
12,13,Star Wars: Episode V - The Empire Strikes Back...,"$67,597,694",2322,"$21,975,993",2111,"Feb 21, 1997",Twentieth Century Fox,False
13,14,Star Wars: Episode VI - Return of the Jedi1997...,"$45,470,437",2111,"$16,293,531",2111,"Mar 14, 1997",Twentieth Century Fox,False
14,15,Star Wars: Episode I - The Phantom Menace2012 ...,"$43,456,382",2655,"$22,469,932",2655,"Feb 10, 2012",Twentieth Century Fox,False
15,16,Star Wars: The Clone Wars,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False
16,17,Star Wars: Episode IV - A New Hope1982 Re-release,"$15,476,785",1070,"$3,766,803",1070,"Aug 13, 1982",Twentieth Century Fox,False
17,18,Star Wars: Episode V - The Empire Strikes Back...,"$13,276,241",1006,"$3,949,478",992,"Nov 19, 1982",Twentieth Century Fox,False
18,19,Star Wars: Episode VI - Return of the Jedi1985...,"$11,252,123",894,"$3,209,056",849,"Mar 29, 1985",Twentieth Century Fox,False
19,20,Star Wars: Episode II - Attack of the Clones20...,"$8,485,488",58,"$1,435,259",58,"Nov 1, 2002",Twentieth Century Fox,False
20,21,Star Wars: Episode VI - Return of the Jedi2023...,"$7,259,924",475,"$5,100,654",475,"Apr 28, 2023",NaN,False
21,22,Star Wars: Episode V - The Empire Strikes Back...,"$2,482,000",2097,"$611,000",611,"Jul 10, 2020",Walt Disney Studios Motion Pictures,True
22,23,Rogue One: A Star Wars Story2022 Re-release,"$1,362,667",255,"$1,060,459",255,"Aug 26, 2022",Walt Disney Studios Motion Pictures,False
23,-,Untitled Taika Waititi Star Wars Film,-,-,-,-,"May 22, 2026",Walt Disney Pictures,False
24,-,Star Wars: New Jedi Order,-,-,-,-,"Dec 17, 2027",Walt Disney Pictures,False

In [39]:
disneystarwars=disneystarwars.drop(disneystarwars.index[11])
disneystarwars

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Star Wars: Episode VII - The Force Awakens,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,False
1,2,Star Wars: Episode VIII - The Last Jedi,"$620,181,382",4232,"$220,009,584",4232,"Dec 15, 2017",Walt Disney Studios Motion Pictures,False
2,3,Rogue One: A Star Wars Story,"$532,177,324",4157,"$155,081,681",4157,"Dec 16, 2016",Walt Disney Studios Motion Pictures,False
3,4,Star Wars: Episode IX - The Rise of Skywalker,"$515,202,542",4406,"$177,383,864",4406,"Dec 20, 2019",Walt Disney Studios Motion Pictures,False
4,5,Star Wars: Episode I - The Phantom Menace,"$431,088,295",3126,"$64,820,970",2970,"May 19, 1999",Twentieth Century Fox,False
5,6,Star Wars: Episode III - Revenge of the Sith,"$380,270,577",3663,"$108,435,841",3661,"May 19, 2005",Twentieth Century Fox,False
6,7,Star Wars: Episode IV - A New Hope,"$307,263,857",1750,"$1,554,475",43,"May 25, 1977",Twentieth Century Fox,False
7,8,Star Wars: Episode II - Attack of the Clones,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False
8,9,Star Wars: Episode VI - Return of the Jedi,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False
9,10,Solo: A Star Wars Story,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,False
10,11,Star Wars: Episode V - The Empire Strikes Back,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False
12,13,Star Wars: Episode V - The Empire Strikes Back...,"$67,597,694",2322,"$21,975,993",2111,"Feb 21, 1997",Twentieth Century Fox,False
13,14,Star Wars: Episode VI - Return of the Jedi1997...,"$45,470,437",2111,"$16,293,531",2111,"Mar 14, 1997",Twentieth Century Fox,False
14,15,Star Wars: Episode I - The Phantom Menace2012 ...,"$43,456,382",2655,"$22,469,932",2655,"Feb 10, 2012",Twentieth Century Fox,False
15,16,Star Wars: The Clone Wars,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False
16,17,Star Wars: Episode IV - A New Hope1982 Re-release,"$15,476,785",1070,"$3,766,803",1070,"Aug 13, 1982",Twentieth Century Fox,False
17,18,Star Wars: Episode V - The Empire Strikes Back...,"$13,276,241",1006,"$3,949,478",992,"Nov 19, 1982",Twentieth Century Fox,False
18,19,Star Wars: Episode VI - Return of the Jedi1985...,"$11,252,123",894,"$3,209,056",849,"Mar 29, 1985",Twentieth Century Fox,False
19,20,Star Wars: Episode II - Attack of the Clones20...,"$8,485,488",58,"$1,435,259",58,"Nov 1, 2002",Twentieth Century Fox,False
20,21,Star Wars: Episode VI - Return of the Jedi2023...,"$7,259,924",475,"$5,100,654",475,"Apr 28, 2023",NaN,False
21,22,Star Wars: Episode V - The Empire Strikes Back...,"$2,482,000",2097,"$611,000",611,"Jul 10, 2020",Walt Disney Studios Motion Pictures,True
22,23,Rogue One: A Star Wars Story2022 Re-release,"$1,362,667",255,"$1,060,459",255,"Aug 26, 2022",Walt Disney Studios Motion Pictures,False
23,-,Untitled Taika Waititi Star Wars Film,-,-,-,-,"May 22, 2026",Walt Disney Pictures,False
24,-,Star Wars: New Jedi Order,-,-,-,-,"Dec 17, 2027",Walt Disney Pictures,False

In [40]:
disneystarwars=disneystarwars.drop(disneystarwars.index[12])
disneystarwars

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Star Wars: Episode VII - The Force Awakens,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,False
1,2,Star Wars: Episode VIII - The Last Jedi,"$620,181,382",4232,"$220,009,584",4232,"Dec 15, 2017",Walt Disney Studios Motion Pictures,False
2,3,Rogue One: A Star Wars Story,"$532,177,324",4157,"$155,081,681",4157,"Dec 16, 2016",Walt Disney Studios Motion Pictures,False
3,4,Star Wars: Episode IX - The Rise of Skywalker,"$515,202,542",4406,"$177,383,864",4406,"Dec 20, 2019",Walt Disney Studios Motion Pictures,False
4,5,Star Wars: Episode I - The Phantom Menace,"$431,088,295",3126,"$64,820,970",2970,"May 19, 1999",Twentieth Century Fox,False
5,6,Star Wars: Episode III - Revenge of the Sith,"$380,270,577",3663,"$108,435,841",3661,"May 19, 2005",Twentieth Century Fox,False
6,7,Star Wars: Episode IV - A New Hope,"$307,263,857",1750,"$1,554,475",43,"May 25, 1977",Twentieth Century Fox,False
7,8,Star Wars: Episode II - Attack of the Clones,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False
8,9,Star Wars: Episode VI - Return of the Jedi,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False
9,10,Solo: A Star Wars Story,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,False
10,11,Star Wars: Episode V - The Empire Strikes Back,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False
12,13,Star Wars: Episode V - The Empire Strikes Back...,"$67,597,694",2322,"$21,975,993",2111,"Feb 21, 1997",Twentieth Century Fox,False
14,15,Star Wars: Episode I - The Phantom Menace2012 ...,"$43,456,382",2655,"$22,469,932",2655,"Feb 10, 2012",Twentieth Century Fox,False
15,16,Star Wars: The Clone Wars,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False
16,17,Star Wars: Episode IV - A New Hope1982 Re-release,"$15,476,785",1070,"$3,766,803",1070,"Aug 13, 1982",Twentieth Century Fox,False
17,18,Star Wars: Episode V - The Empire Strikes Back...,"$13,276,241",1006,"$3,949,478",992,"Nov 19, 1982",Twentieth Century Fox,False
18,19,Star Wars: Episode VI - Return of the Jedi1985...,"$11,252,123",894,"$3,209,056",849,"Mar 29, 1985",Twentieth Century Fox,False
19,20,Star Wars: Episode II - Attack of the Clones20...,"$8,485,488",58,"$1,435,259",58,"Nov 1, 2002",Twentieth Century Fox,False
20,21,Star Wars: Episode VI - Return of the Jedi2023...,"$7,259,924",475,"$5,100,654",475,"Apr 28, 2023",NaN,False
21,22,Star Wars: Episode V - The Empire Strikes Back...,"$2,482,000",2097,"$611,000",611,"Jul 10, 2020",Walt Disney Studios Motion Pictures,True
22,23,Rogue One: A Star Wars Story2022 Re-release,"$1,362,667",255,"$1,060,459",255,"Aug 26, 2022",Walt Disney Studios Motion Pictures,False
23,-,Untitled Taika Waititi Star Wars Film,-,-,-,-,"May 22, 2026",Walt Disney Pictures,False
24,-,Star Wars: New Jedi Order,-,-,-,-,"Dec 17, 2027",Walt Disney Pictures,False

In [41]:
disneystarwars=disneystarwars.drop(disneystarwars.index[12])
disneystarwars

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Star Wars: Episode VII - The Force Awakens,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,False
1,2,Star Wars: Episode VIII - The Last Jedi,"$620,181,382",4232,"$220,009,584",4232,"Dec 15, 2017",Walt Disney Studios Motion Pictures,False
2,3,Rogue One: A Star Wars Story,"$532,177,324",4157,"$155,081,681",4157,"Dec 16, 2016",Walt Disney Studios Motion Pictures,False
3,4,Star Wars: Episode IX - The Rise of Skywalker,"$515,202,542",4406,"$177,383,864",4406,"Dec 20, 2019",Walt Disney Studios Motion Pictures,False
4,5,Star Wars: Episode I - The Phantom Menace,"$431,088,295",3126,"$64,820,970",2970,"May 19, 1999",Twentieth Century Fox,False
5,6,Star Wars: Episode III - Revenge of the Sith,"$380,270,577",3663,"$108,435,841",3661,"May 19, 2005",Twentieth Century Fox,False
6,7,Star Wars: Episode IV - A New Hope,"$307,263,857",1750,"$1,554,475",43,"May 25, 1977",Twentieth Century Fox,False
7,8,Star Wars: Episode II - Attack of the Clones,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False
8,9,Star Wars: Episode VI - Return of the Jedi,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False
9,10,Solo: A Star Wars Story,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,False
10,11,Star Wars: Episode V - The Empire Strikes Back,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False
12,13,Star Wars: Episode V - The Empire Strikes Back...,"$67,597,694",2322,"$21,975,993",2111,"Feb 21, 1997",Twentieth Century Fox,False
15,16,Star Wars: The Clone Wars,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False
16,17,Star Wars: Episode IV - A New Hope1982 Re-release,"$15,476,785",1070,"$3,766,803",1070,"Aug 13, 1982",Twentieth Century Fox,False
17,18,Star Wars: Episode V - The Empire Strikes Back...,"$13,276,241",1006,"$3,949,478",992,"Nov 19, 1982",Twentieth Century Fox,False
18,19,Star Wars: Episode VI - Return of the Jedi1985...,"$11,252,123",894,"$3,209,056",849,"Mar 29, 1985",Twentieth Century Fox,False
19,20,Star Wars: Episode II - Attack of the Clones20...,"$8,485,488",58,"$1,435,259",58,"Nov 1, 2002",Twentieth Century Fox,False
20,21,Star Wars: Episode VI - Return of the Jedi2023...,"$7,259,924",475,"$5,100,654",475,"Apr 28, 2023",NaN,False
21,22,Star Wars: Episode V - The Empire Strikes Back...,"$2,482,000",2097,"$611,000",611,"Jul 10, 2020",Walt Disney Studios Motion Pictures,True
22,23,Rogue One: A Star Wars Story2022 Re-release,"$1,362,667",255,"$1,060,459",255,"Aug 26, 2022",Walt Disney Studios Motion Pictures,False
23,-,Untitled Taika Waititi Star Wars Film,-,-,-,-,"May 22, 2026",Walt Disney Pictures,False
24,-,Star Wars: New Jedi Order,-,-,-,-,"Dec 17, 2027",Walt Disney Pictures,False

In [42]:
disneystarwars=disneystarwars.drop(disneystarwars.index[11])
disneystarwars

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Star Wars: Episode VII - The Force Awakens,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,False
1,2,Star Wars: Episode VIII - The Last Jedi,"$620,181,382",4232,"$220,009,584",4232,"Dec 15, 2017",Walt Disney Studios Motion Pictures,False
2,3,Rogue One: A Star Wars Story,"$532,177,324",4157,"$155,081,681",4157,"Dec 16, 2016",Walt Disney Studios Motion Pictures,False
3,4,Star Wars: Episode IX - The Rise of Skywalker,"$515,202,542",4406,"$177,383,864",4406,"Dec 20, 2019",Walt Disney Studios Motion Pictures,False
4,5,Star Wars: Episode I - The Phantom Menace,"$431,088,295",3126,"$64,820,970",2970,"May 19, 1999",Twentieth Century Fox,False
5,6,Star Wars: Episode III - Revenge of the Sith,"$380,270,577",3663,"$108,435,841",3661,"May 19, 2005",Twentieth Century Fox,False
6,7,Star Wars: Episode IV - A New Hope,"$307,263,857",1750,"$1,554,475",43,"May 25, 1977",Twentieth Century Fox,False
7,8,Star Wars: Episode II - Attack of the Clones,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False
8,9,Star Wars: Episode VI - Return of the Jedi,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False
9,10,Solo: A Star Wars Story,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,False
10,11,Star Wars: Episode V - The Empire Strikes Back,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False
15,16,Star Wars: The Clone Wars,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False
16,17,Star Wars: Episode IV - A New Hope1982 Re-release,"$15,476,785",1070,"$3,766,803",1070,"Aug 13, 1982",Twentieth Century Fox,False
17,18,Star Wars: Episode V - The Empire Strikes Back...,"$13,276,241",1006,"$3,949,478",992,"Nov 19, 1982",Twentieth Century Fox,False
18,19,Star Wars: Episode VI - Return of the Jedi1985...,"$11,252,123",894,"$3,209,056",849,"Mar 29, 1985",Twentieth Century Fox,False
19,20,Star Wars: Episode II - Attack of the Clones20...,"$8,485,488",58,"$1,435,259",58,"Nov 1, 2002",Twentieth Century Fox,False
20,21,Star Wars: Episode VI - Return of the Jedi2023...,"$7,259,924",475,"$5,100,654",475,"Apr 28, 2023",NaN,False
21,22,Star Wars: Episode V - The Empire Strikes Back...,"$2,482,000",2097,"$611,000",611,"Jul 10, 2020",Walt Disney Studios Motion Pictures,True
22,23,Rogue One: A Star Wars Story2022 Re-release,"$1,362,667",255,"$1,060,459",255,"Aug 26, 2022",Walt Disney Studios Motion Pictures,False
23,-,Untitled Taika Waititi Star Wars Film,-,-,-,-,"May 22, 2026",Walt Disney Pictures,False
24,-,Star Wars: New Jedi Order,-,-,-,-,"Dec 17, 2027",Walt Disney Pictures,False

In [43]:
disneystarwars=disneystarwars.drop(disneystarwars.index[12:])
disneystarwars

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Star Wars: Episode VII - The Force Awakens,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,False
1,2,Star Wars: Episode VIII - The Last Jedi,"$620,181,382",4232,"$220,009,584",4232,"Dec 15, 2017",Walt Disney Studios Motion Pictures,False
2,3,Rogue One: A Star Wars Story,"$532,177,324",4157,"$155,081,681",4157,"Dec 16, 2016",Walt Disney Studios Motion Pictures,False
3,4,Star Wars: Episode IX - The Rise of Skywalker,"$515,202,542",4406,"$177,383,864",4406,"Dec 20, 2019",Walt Disney Studios Motion Pictures,False
4,5,Star Wars: Episode I - The Phantom Menace,"$431,088,295",3126,"$64,820,970",2970,"May 19, 1999",Twentieth Century Fox,False
5,6,Star Wars: Episode III - Revenge of the Sith,"$380,270,577",3663,"$108,435,841",3661,"May 19, 2005",Twentieth Century Fox,False
6,7,Star Wars: Episode IV - A New Hope,"$307,263,857",1750,"$1,554,475",43,"May 25, 1977",Twentieth Century Fox,False
7,8,Star Wars: Episode II - Attack of the Clones,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False
8,9,Star Wars: Episode VI - Return of the Jedi,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False
9,10,Solo: A Star Wars Story,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,False
10,11,Star Wars: Episode V - The Empire Strikes Back,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False
15,16,Star Wars: The Clone Wars,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False

In [44]:
disneystarwars=disneystarwars.reset_index()
disneystarwars

,index,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,0,1,Star Wars: Episode VII - The Force Awakens,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,False
1,1,2,Star Wars: Episode VIII - The Last Jedi,"$620,181,382",4232,"$220,009,584",4232,"Dec 15, 2017",Walt Disney Studios Motion Pictures,False
2,2,3,Rogue One: A Star Wars Story,"$532,177,324",4157,"$155,081,681",4157,"Dec 16, 2016",Walt Disney Studios Motion Pictures,False
3,3,4,Star Wars: Episode IX - The Rise of Skywalker,"$515,202,542",4406,"$177,383,864",4406,"Dec 20, 2019",Walt Disney Studios Motion Pictures,False
4,4,5,Star Wars: Episode I - The Phantom Menace,"$431,088,295",3126,"$64,820,970",2970,"May 19, 1999",Twentieth Century Fox,False
5,5,6,Star Wars: Episode III - Revenge of the Sith,"$380,270,577",3663,"$108,435,841",3661,"May 19, 2005",Twentieth Century Fox,False
6,6,7,Star Wars: Episode IV - A New Hope,"$307,263,857",1750,"$1,554,475",43,"May 25, 1977",Twentieth Century Fox,False
7,7,8,Star Wars: Episode II - Attack of the Clones,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False
8,8,9,Star Wars: Episode VI - Return of the Jedi,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False
9,9,10,Solo: A Star Wars Story,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,False
10,10,11,Star Wars: Episode V - The Empire Strikes Back,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False
11,15,16,Star Wars: The Clone Wars,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False

In [45]:
disneystarwars=disneystarwars.drop(['index'], axis=1)
disneystarwars

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Star Wars: Episode VII - The Force Awakens,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,False
1,2,Star Wars: Episode VIII - The Last Jedi,"$620,181,382",4232,"$220,009,584",4232,"Dec 15, 2017",Walt Disney Studios Motion Pictures,False
2,3,Rogue One: A Star Wars Story,"$532,177,324",4157,"$155,081,681",4157,"Dec 16, 2016",Walt Disney Studios Motion Pictures,False
3,4,Star Wars: Episode IX - The Rise of Skywalker,"$515,202,542",4406,"$177,383,864",4406,"Dec 20, 2019",Walt Disney Studios Motion Pictures,False
4,5,Star Wars: Episode I - The Phantom Menace,"$431,088,295",3126,"$64,820,970",2970,"May 19, 1999",Twentieth Century Fox,False
5,6,Star Wars: Episode III - Revenge of the Sith,"$380,270,577",3663,"$108,435,841",3661,"May 19, 2005",Twentieth Century Fox,False
6,7,Star Wars: Episode IV - A New Hope,"$307,263,857",1750,"$1,554,475",43,"May 25, 1977",Twentieth Century Fox,False
7,8,Star Wars: Episode II - Attack of the Clones,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False
8,9,Star Wars: Episode VI - Return of the Jedi,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False
9,10,Solo: A Star Wars Story,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,False
10,11,Star Wars: Episode V - The Empire Strikes Back,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False
11,16,Star Wars: The Clone Wars,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False

In [46]:
disneystarwars['category'] = 'starwars'
disneystarwars

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,Star Wars: Episode VII - The Force Awakens,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,False,starwars
1,2,Star Wars: Episode VIII - The Last Jedi,"$620,181,382",4232,"$220,009,584",4232,"Dec 15, 2017",Walt Disney Studios Motion Pictures,False,starwars
2,3,Rogue One: A Star Wars Story,"$532,177,324",4157,"$155,081,681",4157,"Dec 16, 2016",Walt Disney Studios Motion Pictures,False,starwars
3,4,Star Wars: Episode IX - The Rise of Skywalker,"$515,202,542",4406,"$177,383,864",4406,"Dec 20, 2019",Walt Disney Studios Motion Pictures,False,starwars
4,5,Star Wars: Episode I - The Phantom Menace,"$431,088,295",3126,"$64,820,970",2970,"May 19, 1999",Twentieth Century Fox,False,starwars
5,6,Star Wars: Episode III - Revenge of the Sith,"$380,270,577",3663,"$108,435,841",3661,"May 19, 2005",Twentieth Century Fox,False,starwars
6,7,Star Wars: Episode IV - A New Hope,"$307,263,857",1750,"$1,554,475",43,"May 25, 1977",Twentieth Century Fox,False,starwars
7,8,Star Wars: Episode II - Attack of the Clones,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False,starwars
8,9,Star Wars: Episode VI - Return of the Jedi,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False,starwars
9,10,Solo: A Star Wars Story,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,False,starwars
10,11,Star Wars: Episode V - The Empire Strikes Back,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False,starwars
11,16,Star Wars: The Clone Wars,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False,starwars

In [47]:
lmpss = pd.concat([lmps, disneystarwars])
lmpss

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False,live reimaginings
2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False,live reimaginings
...,...,...,...,...,...,...,...,...,...,...
7,8,Star Wars: Episode II - Attack of the Clones,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False,starwars
8,9,Star Wars: Episode VI - Return of the Jedi,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False,starwars
9,10,Solo: A Star Wars Story,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,False,starwars
10,11,Star Wars: Episode V - The Empire Strikes Back,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False,starwars
11,16,Star Wars: The Clone Wars,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False,starwars

In [48]:
lmpss=lmpss.reset_index()
lmpss

,index,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
1,1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False,live reimaginings
2,2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
3,3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
4,4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False,live reimaginings
...,...,...,...,...,...,...,...,...,...,...,...
87,7,8,Star Wars: Episode II - Attack of the Clones,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False,starwars
88,8,9,Star Wars: Episode VI - Return of the Jedi,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False,starwars
89,9,10,Solo: A Star Wars Story,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,False,starwars
90,10,11,Star Wars: Episode V - The Empire Strikes Back,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False,starwars
91,11,16,Star Wars: The Clone Wars,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False,starwars

In [49]:
lmpss=lmpss.drop(['index'], axis=1)
lmpss

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False,live reimaginings
2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False,live reimaginings
...,...,...,...,...,...,...,...,...,...,...
87,8,Star Wars: Episode II - Attack of the Clones,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False,starwars
88,9,Star Wars: Episode VI - Return of the Jedi,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False,starwars
89,10,Solo: A Star Wars Story,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,False,starwars
90,11,Star Wars: Episode V - The Empire Strikes Back,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False,starwars
91,16,Star Wars: The Clone Wars,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False,starwars

lmpss=lmpss.drop(['level_0'], axis=1)
lmpss

In [50]:
disneywdanimation

,Unnamed: 0,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,0,1,Frozen II,"$477,373,578",4440,"$130,263,358",4440,"Nov 22, 2019",Walt Disney Studios Motion Pictures,False
1,1,2,Frozen,"$400,738,009",3742,"$243,390",1,"Nov 22, 2013",Walt Disney Studios Motion Pictures,False
2,2,3,Zootopia,"$341,268,248",3959,"$75,063,401",3827,"Mar 4, 2016",Walt Disney Studios Motion Pictures,False
3,3,4,Moana,"$248,757,044",3875,"$56,631,401",3875,"Nov 23, 2016",Walt Disney Studios Motion Pictures,False
4,4,5,Big Hero 6,"$222,527,828",3773,"$56,215,889",3761,"Nov 7, 2014",Walt Disney Studios Motion Pictures,False
5,5,6,Ralph Breaks the Internet,"$201,091,711",4017,"$56,237,634",4017,"Nov 21, 2018",Walt Disney Studios Motion Pictures,False
6,6,7,Tangled,"$200,821,936",3603,"$48,767,052",3603,"Nov 24, 2010",Walt Disney Studios Motion Pictures,False
7,7,8,Wreck-It Ralph,"$189,422,889",3752,"$49,038,712",3752,"Nov 2, 2012",Walt Disney Studios Motion Pictures,False
8,8,9,Bolt,"$114,053,579",3654,"$26,223,128",3651,"Nov 21, 2008",Walt Disney Studios Motion Pictures,False
9,9,10,The Princess and the Frog,"$104,400,899",3475,"$786,190",2,"Nov 25, 2009",Walt Disney Studios Motion Pictures,False
10,10,11,Meet the Robinsons,"$97,822,171",3435,"$25,123,781",3413,"Mar 30, 2007",Walt Disney Studios Motion Pictures,False
11,11,12,Encanto,"$96,093,622",3980,"$27,206,494",3980,"Nov 24, 2021",Walt Disney Studios Motion Pictures,False
12,12,13,Raya and the Last Dragon,"$54,723,032",2375,"$8,502,498",2045,"Mar 5, 2021",Walt Disney Studios Motion Pictures,False
13,13,14,Winnie the Pooh,"$26,692,846",2405,"$7,857,076",2405,"Jul 15, 2011",Walt Disney Studios Motion Pictures,False
14,14,15,Frozen2020 Re-release,"$215,000",1367,"$120,000",1367,"Nov 25, 2020",Walt Disney Studios Motion Pictures,True

In [51]:
disneywdanimation=disneywdanimation.drop(['Unnamed: 0'], axis=1)
disneywdanimation

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Frozen II,"$477,373,578",4440,"$130,263,358",4440,"Nov 22, 2019",Walt Disney Studios Motion Pictures,False
1,2,Frozen,"$400,738,009",3742,"$243,390",1,"Nov 22, 2013",Walt Disney Studios Motion Pictures,False
2,3,Zootopia,"$341,268,248",3959,"$75,063,401",3827,"Mar 4, 2016",Walt Disney Studios Motion Pictures,False
3,4,Moana,"$248,757,044",3875,"$56,631,401",3875,"Nov 23, 2016",Walt Disney Studios Motion Pictures,False
4,5,Big Hero 6,"$222,527,828",3773,"$56,215,889",3761,"Nov 7, 2014",Walt Disney Studios Motion Pictures,False
5,6,Ralph Breaks the Internet,"$201,091,711",4017,"$56,237,634",4017,"Nov 21, 2018",Walt Disney Studios Motion Pictures,False
6,7,Tangled,"$200,821,936",3603,"$48,767,052",3603,"Nov 24, 2010",Walt Disney Studios Motion Pictures,False
7,8,Wreck-It Ralph,"$189,422,889",3752,"$49,038,712",3752,"Nov 2, 2012",Walt Disney Studios Motion Pictures,False
8,9,Bolt,"$114,053,579",3654,"$26,223,128",3651,"Nov 21, 2008",Walt Disney Studios Motion Pictures,False
9,10,The Princess and the Frog,"$104,400,899",3475,"$786,190",2,"Nov 25, 2009",Walt Disney Studios Motion Pictures,False
10,11,Meet the Robinsons,"$97,822,171",3435,"$25,123,781",3413,"Mar 30, 2007",Walt Disney Studios Motion Pictures,False
11,12,Encanto,"$96,093,622",3980,"$27,206,494",3980,"Nov 24, 2021",Walt Disney Studios Motion Pictures,False
12,13,Raya and the Last Dragon,"$54,723,032",2375,"$8,502,498",2045,"Mar 5, 2021",Walt Disney Studios Motion Pictures,False
13,14,Winnie the Pooh,"$26,692,846",2405,"$7,857,076",2405,"Jul 15, 2011",Walt Disney Studios Motion Pictures,False
14,15,Frozen2020 Re-release,"$215,000",1367,"$120,000",1367,"Nov 25, 2020",Walt Disney Studios Motion Pictures,True

In [52]:
disneywdanimation=disneywdanimation.drop(disneywdanimation.index[14])
disneywdanimation

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated
0,1,Frozen II,"$477,373,578",4440,"$130,263,358",4440,"Nov 22, 2019",Walt Disney Studios Motion Pictures,False
1,2,Frozen,"$400,738,009",3742,"$243,390",1,"Nov 22, 2013",Walt Disney Studios Motion Pictures,False
2,3,Zootopia,"$341,268,248",3959,"$75,063,401",3827,"Mar 4, 2016",Walt Disney Studios Motion Pictures,False
3,4,Moana,"$248,757,044",3875,"$56,631,401",3875,"Nov 23, 2016",Walt Disney Studios Motion Pictures,False
4,5,Big Hero 6,"$222,527,828",3773,"$56,215,889",3761,"Nov 7, 2014",Walt Disney Studios Motion Pictures,False
5,6,Ralph Breaks the Internet,"$201,091,711",4017,"$56,237,634",4017,"Nov 21, 2018",Walt Disney Studios Motion Pictures,False
6,7,Tangled,"$200,821,936",3603,"$48,767,052",3603,"Nov 24, 2010",Walt Disney Studios Motion Pictures,False
7,8,Wreck-It Ralph,"$189,422,889",3752,"$49,038,712",3752,"Nov 2, 2012",Walt Disney Studios Motion Pictures,False
8,9,Bolt,"$114,053,579",3654,"$26,223,128",3651,"Nov 21, 2008",Walt Disney Studios Motion Pictures,False
9,10,The Princess and the Frog,"$104,400,899",3475,"$786,190",2,"Nov 25, 2009",Walt Disney Studios Motion Pictures,False
10,11,Meet the Robinsons,"$97,822,171",3435,"$25,123,781",3413,"Mar 30, 2007",Walt Disney Studios Motion Pictures,False
11,12,Encanto,"$96,093,622",3980,"$27,206,494",3980,"Nov 24, 2021",Walt Disney Studios Motion Pictures,False
12,13,Raya and the Last Dragon,"$54,723,032",2375,"$8,502,498",2045,"Mar 5, 2021",Walt Disney Studios Motion Pictures,False
13,14,Winnie the Pooh,"$26,692,846",2405,"$7,857,076",2405,"Jul 15, 2011",Walt Disney Studios Motion Pictures,False

In [53]:
disneywdanimation['category'] = 'animated'
disneywdanimation

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,Frozen II,"$477,373,578",4440,"$130,263,358",4440,"Nov 22, 2019",Walt Disney Studios Motion Pictures,False,animated
1,2,Frozen,"$400,738,009",3742,"$243,390",1,"Nov 22, 2013",Walt Disney Studios Motion Pictures,False,animated
2,3,Zootopia,"$341,268,248",3959,"$75,063,401",3827,"Mar 4, 2016",Walt Disney Studios Motion Pictures,False,animated
3,4,Moana,"$248,757,044",3875,"$56,631,401",3875,"Nov 23, 2016",Walt Disney Studios Motion Pictures,False,animated
4,5,Big Hero 6,"$222,527,828",3773,"$56,215,889",3761,"Nov 7, 2014",Walt Disney Studios Motion Pictures,False,animated
5,6,Ralph Breaks the Internet,"$201,091,711",4017,"$56,237,634",4017,"Nov 21, 2018",Walt Disney Studios Motion Pictures,False,animated
6,7,Tangled,"$200,821,936",3603,"$48,767,052",3603,"Nov 24, 2010",Walt Disney Studios Motion Pictures,False,animated
7,8,Wreck-It Ralph,"$189,422,889",3752,"$49,038,712",3752,"Nov 2, 2012",Walt Disney Studios Motion Pictures,False,animated
8,9,Bolt,"$114,053,579",3654,"$26,223,128",3651,"Nov 21, 2008",Walt Disney Studios Motion Pictures,False,animated
9,10,The Princess and the Frog,"$104,400,899",3475,"$786,190",2,"Nov 25, 2009",Walt Disney Studios Motion Pictures,False,animated
10,11,Meet the Robinsons,"$97,822,171",3435,"$25,123,781",3413,"Mar 30, 2007",Walt Disney Studios Motion Pictures,False,animated
11,12,Encanto,"$96,093,622",3980,"$27,206,494",3980,"Nov 24, 2021",Walt Disney Studios Motion Pictures,False,animated
12,13,Raya and the Last Dragon,"$54,723,032",2375,"$8,502,498",2045,"Mar 5, 2021",Walt Disney Studios Motion Pictures,False,animated
13,14,Winnie the Pooh,"$26,692,846",2405,"$7,857,076",2405,"Jul 15, 2011",Walt Disney Studios Motion Pictures,False,animated

In [54]:
lmpssa = pd.concat([lmpss, disneywdanimation])
lmpssa

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False,live reimaginings
2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False,live reimaginings
...,...,...,...,...,...,...,...,...,...,...
9,10,The Princess and the Frog,"$104,400,899",3475,"$786,190",2,"Nov 25, 2009",Walt Disney Studios Motion Pictures,False,animated
10,11,Meet the Robinsons,"$97,822,171",3435,"$25,123,781",3413,"Mar 30, 2007",Walt Disney Studios Motion Pictures,False,animated
11,12,Encanto,"$96,093,622",3980,"$27,206,494",3980,"Nov 24, 2021",Walt Disney Studios Motion Pictures,False,animated
12,13,Raya and the Last Dragon,"$54,723,032",2375,"$8,502,498",2045,"Mar 5, 2021",Walt Disney Studios Motion Pictures,False,animated
13,14,Winnie the Pooh,"$26,692,846",2405,"$7,857,076",2405,"Jul 15, 2011",Walt Disney Studios Motion Pictures,False,animated

In [55]:
lmpssa=lmpssa.reset_index()
lmpssa

,index,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
1,1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False,live reimaginings
2,2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
3,3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
4,4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False,live reimaginings
...,...,...,...,...,...,...,...,...,...,...,...
101,9,10,The Princess and the Frog,"$104,400,899",3475,"$786,190",2,"Nov 25, 2009",Walt Disney Studios Motion Pictures,False,animated
102,10,11,Meet the Robinsons,"$97,822,171",3435,"$25,123,781",3413,"Mar 30, 2007",Walt Disney Studios Motion Pictures,False,animated
103,11,12,Encanto,"$96,093,622",3980,"$27,206,494",3980,"Nov 24, 2021",Walt Disney Studios Motion Pictures,False,animated
104,12,13,Raya and the Last Dragon,"$54,723,032",2375,"$8,502,498",2045,"Mar 5, 2021",Walt Disney Studios Motion Pictures,False,animated
105,13,14,Winnie the Pooh,"$26,692,846",2405,"$7,857,076",2405,"Jul 15, 2011",Walt Disney Studios Motion Pictures,False,animated

In [56]:
lmpssa=lmpssa.drop(['index'], axis=1)
lmpssa

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False,live reimaginings
2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False,live reimaginings
...,...,...,...,...,...,...,...,...,...,...
101,10,The Princess and the Frog,"$104,400,899",3475,"$786,190",2,"Nov 25, 2009",Walt Disney Studios Motion Pictures,False,animated
102,11,Meet the Robinsons,"$97,822,171",3435,"$25,123,781",3413,"Mar 30, 2007",Walt Disney Studios Motion Pictures,False,animated
103,12,Encanto,"$96,093,622",3980,"$27,206,494",3980,"Nov 24, 2021",Walt Disney Studios Motion Pictures,False,animated
104,13,Raya and the Last Dragon,"$54,723,032",2375,"$8,502,498",2045,"Mar 5, 2021",Walt Disney Studios Motion Pictures,False,animated
105,14,Winnie the Pooh,"$26,692,846",2405,"$7,857,076",2405,"Jul 15, 2011",Walt Disney Studios Motion Pictures,False,animated

In [57]:
disneytotal = pd.read_csv('data/disney_movies_total_gross.csv')

In [58]:
disneytotal

,movie_title,release_date,genre,mpaa_rating,total_gross,inflation_adjusted_gross
0,Snow White and the Seven Dwarfs,1937-12-21,Musical,G,184925485,5228953251
1,Pinocchio,1940-02-09,Adventure,G,84300000,2188229052
2,Fantasia,1940-11-13,Musical,G,83320000,2187090808
3,Song of the South,1946-11-12,Adventure,G,65000000,1078510579
4,Cinderella,1950-02-15,Drama,G,85000000,920608730
...,...,...,...,...,...,...
574,The Light Between Oceans,2016-09-02,Drama,PG-13,12545979,12545979
575,Queen of Katwe,2016-09-23,Drama,PG,8874389,8874389
576,Doctor Strange,2016-11-04,Adventure,PG-13,232532923,232532923
577,Moana,2016-11-23,Adventure,PG,246082029,246082029
578,Rogue One: A Star Wars Story,2016-12-16,Adventure,PG-13,529483936,529483936

In [59]:
disneymovies = pd.read_csv('data/disney_movie_data_final.csv')

In [60]:
disneymovies

,Unnamed: 0,title,Production company,Release date,Running time,Country,Language,Running time (int),Budget (float),Box office (float),...,Box office,Story by,Narrated by,Cinematography,Edited by,Screenplay by,Production companies,Adaptation by,Traditional,Simplified
0,0,Academy Award Review of,Walt Disney Productions,"['May 19, 1937']",41 minutes (74 minutes 1966 release),United States,English,41.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Snow White and the Seven Dwarfs,Walt Disney Productions,"['December 21, 1937 ( Carthay Circle Theatre ,...",83 minutes,United States,English,83.0,1490000.0,418000000.0,...,$418 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Pinocchio,Walt Disney Productions,"['February 7, 1940 ( Center Theatre )', 'Febru...",88 minutes,United States,English,88.0,2600000.0,164000000.0,...,$164 million,"['Ted Sears', 'Otto Englander', 'Webb Smith', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Fantasia,Walt Disney Productions,"['November 13, 1940']",126 minutes,United States,English,126.0,2280000.0,83300000.0,...,$76.4–$83.3 million,"['Joe Grant', 'Dick Huemer']",Deems Taylor,James Wong Howe,NaN,NaN,NaN,NaN,NaN,NaN
4,4,The Reluctant Dragon,Walt Disney Productions,"['June 20, 1941']",74 minutes,United States,English,74.0,600000.0,960000.0,...,"$960,000 (worldwide rentals)",NaN,NaN,Bert Giennon,Paul Weatherwax,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,427,Soul,"['Walt Disney Pictures', 'Pixar Animation Stud...","['October 15, 2020 ( Rome Film Festival )', 'N...",NaN,United States,English,NaN,150000000.0,NaN,...,NaN,Pete Docter,NaN,NaN,NaN,"['Pete Docter', 'Mike Jones', 'Kemp Powers']",NaN,NaN,NaN,NaN
428,428,Raya and the Last Dragon,"['Walt Disney Pictures', 'Walt Disney Animatio...","['March 12, 2021']",NaN,United States,English,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429,429,Cruella,"['Walt Disney Pictures', 'Gunn Films', 'Marc P...","['May 28, 2021 (United States)']",NaN,United States,English,NaN,NaN,NaN,...,NaN,NaN,NaN,Nicolas Karakatsanis,Tatiana S. Riegel,"['Aline Brosh McKenna', 'Jez Butterworth', 'Da...",NaN,NaN,NaN,NaN
430,430,Jungle Cruise,"['Walt Disney Pictures', 'Davis Entertainment'...","['July 30, 2021 (United States)']",NaN,United States,English,NaN,NaN,NaN,...,NaN,"['Glenn Ficarra', 'John Requa']",NaN,Flavio Labiano,Joel Negron,"['Michael Green', 'Glenn Ficarra', 'John Requa']",NaN,NaN,NaN,NaN
431,431,The Beatles: Get Back,NaN,['27 August 2021'],NaN,"['United Kingdom', 'New Zealand', 'United Stat...",English,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Jabez Olssen,NaN,"['Walt Disney Pictures', 'Apple Corps', 'WingN...",NaN,NaN,NaN

In [61]:
disneymovies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               432 non-null    int64
 1   title                    432 non-null    object
 2   Production company       392 non-null    object
 3   Release date             431 non-null    object
 4   Running time             422 non-null    object
 5   Country                  428 non-null    object
 6   Language                 430 non-null    object
 7   Running time (int)       422 non-null    float64
 8   Budget (float)           273 non-null    float64
 9   Box office (float)       355 non-null    float64
 10  Release date (datetime)  428 non-null    object
 11  imdb                     416 non-null    float64
 12  metascore                283 non-null    float64
 13  rotten_tomatoes          361 non-null    object
 14  Directed by              431 non-null    object
 15  Produced by              422 non-null    object
 16  Written by               203 non-null    object
 17  Based on                 211 non-null    object
 18  Starring                 398 non-null    object
 19  Music by                 422 non-null    object
 20  Distributed by           429 non-null    object
 21  Budget                   276 non-null    object
 22  Box office               359 non-null    object
 23  Story by                 139 non-null    object
 24  Narrated by              55 non-null     object
 25  Cinematography           342 non-null    object
 26  Edited by                395 non-null    object
 27  Screenplay by            191 non-null    object
 28  Production companies     39 non-null     object
 29  Adaptation by            1 non-null      object
 30  Traditional              1 non-null      object
 31  Simplified               1 non-null      object
dtypes: float64(5), int64(1), object(26)
memory usage: 108.1+ KB

In [62]:
disneymovies=disneymovies.drop(['Simplified','Traditional','Adaptation by','Screenplay by','Edited by','Narrated by','Cinematography','Story by'], axis=1)
disneymovies

,Unnamed: 0,title,Production company,Release date,Running time,Country,Language,Running time (int),Budget (float),Box office (float),...,Directed by,Produced by,Written by,Based on,Starring,Music by,Distributed by,Budget,Box office,Production companies
0,0,Academy Award Review of,Walt Disney Productions,"['May 19, 1937']",41 minutes (74 minutes 1966 release),United States,English,41.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Snow White and the Seven Dwarfs,Walt Disney Productions,"['December 21, 1937 ( Carthay Circle Theatre ,...",83 minutes,United States,English,83.0,1490000.0,418000000.0,...,"['David Hand (supervising)', 'William Cottrell...",Walt Disney,"['Ted Sears', 'Richard Creedon', 'Otto England...","['Snow White', 'by The', 'Brothers Grimm']","['Adriana Caselotti', 'Lucille La Verne', 'Har...","['Frank Churchill', 'Paul Smith', 'Leigh Harli...",RKO Radio Pictures,$1.49 million,$418 million,NaN
2,2,Pinocchio,Walt Disney Productions,"['February 7, 1940 ( Center Theatre )', 'Febru...",88 minutes,United States,English,88.0,2600000.0,164000000.0,...,"['Ben Sharpsteen', 'Hamilton Luske', 'Bill Rob...",Walt Disney,NaN,"['The Adventures of Pinocchio', 'by', 'Carlo C...","['Cliff Edwards', 'Dickie Jones', 'Christian R...","['Leigh Harline', 'Paul J. Smith']",RKO Radio Pictures,$2.6 million,$164 million,NaN
3,3,Fantasia,Walt Disney Productions,"['November 13, 1940']",126 minutes,United States,English,126.0,2280000.0,83300000.0,...,"['Samuel Armstrong', 'James Algar', 'Bill Robe...","['Walt Disney', 'Ben Sharpsteen']",NaN,NaN,"['Leopold Stokowski', 'Deems Taylor']",See program,"['Walt Disney Productions', 'RKO Radio Pictures']",$2.28 million,$76.4–$83.3 million,NaN
4,4,The Reluctant Dragon,Walt Disney Productions,"['June 20, 1941']",74 minutes,United States,English,74.0,600000.0,960000.0,...,"['Alfred Werker', '(live action)', 'Hamilton L...",Walt Disney,"['Live-action:', 'Ted Sears', 'Al Perkins', 'L...",NaN,"['Robert Benchley', 'Frances Gifford', 'Buddy ...","['Frank Churchill', 'Larry Morey']",RKO Radio Pictures,"$600,000","$960,000 (worldwide rentals)",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,427,Soul,"['Walt Disney Pictures', 'Pixar Animation Stud...","['October 15, 2020 ( Rome Film Festival )', 'N...",NaN,United States,English,NaN,150000000.0,NaN,...,Pete Docter,Dana Murray,NaN,NaN,"['Jamie Foxx', 'Tina Fey', 'Questlove', 'Phyli...","['Trent Reznor', 'Atticus Ross']","['Walt Disney Studios', 'Motion Pictures']",$150 million+,NaN,NaN
428,428,Raya and the Last Dragon,"['Walt Disney Pictures', 'Walt Disney Animatio...","['March 12, 2021']",NaN,United States,English,NaN,NaN,NaN,...,"['Don Hall', 'Carlos López Estrada']","['Osnat Shurer', 'Peter Del Vecho']","['Qui Nguyen', 'Adele Lim']",NaN,"['Kelly Marie Tran', 'Awkwafina']",NaN,"['Walt Disney Studios', 'Motion Pictures']",NaN,NaN,NaN
429,429,Cruella,"['Walt Disney Pictures', 'Gunn Films', 'Marc P...","['May 28, 2021 (United States)']",NaN,United States,English,NaN,NaN,NaN,...,Craig Gillespie,"['Kristin Burr', 'Andrew Gunn', 'Marc Platt']",NaN,"[""Disney's One Hundred and One Dalmatians by B...","['Emma Stone', 'Emma Thompson', 'Paul Walter H...",NaN,Walt Disney Studios Motion Pictures,NaN,NaN,NaN
430,430,Jungle Cruise,"['Walt Disney Pictures', 'Davis Entertainment'...","['July 30, 2021 (United States)']",NaN,United States,English,NaN,NaN,NaN,...,Jaume Collet-Serra,"['John Davis', 'John Fox', 'Beau Flynn', 'Dway...",NaN,"['Jungle Cruise', 'by', 'Walt Disney']","['Dwayne Johnson', 'Emily Blunt', 'Édgar Ramír...","['James Newton Howard', 'Metallica']",Walt Disney Studios Motion Pictures,NaN,NaN,NaN
431,431,The Beatles: Get Back,NaN,['27 August 2021'],NaN,"['United Kingdom', 'New Zealand', 'United Stat...",English,NaN,NaN,NaN,...,Peter Jackson,"['Peter Jackson', 'Clare Olssen', 'Jonathan Cl...",NaN,NaN,The Beatles,The Beatles,"['Walt Disney Studios', 'Motion Pictures']",NaN,NaN,"['Walt Disney Pictures', 'Apple Corps', 'WingN..."

In [63]:
disneymovies=disneymovies.drop(['Unnamed: 0','Language','Based on'], axis=1)
disneymovies

,title,Production company,Release date,Running time,Country,Running time (int),Budget (float),Box office (float),Release date (datetime),imdb,...,rotten_tomatoes,Directed by,Produced by,Written by,Starring,Music by,Distributed by,Budget,Box office,Production companies
0,Academy Award Review of,Walt Disney Productions,"['May 19, 1937']",41 minutes (74 minutes 1966 release),United States,41.0,NaN,NaN,1937-05-19,7.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Snow White and the Seven Dwarfs,Walt Disney Productions,"['December 21, 1937 ( Carthay Circle Theatre ,...",83 minutes,United States,83.0,1490000.0,418000000.0,1937-12-21,7.6,...,NaN,"['David Hand (supervising)', 'William Cottrell...",Walt Disney,"['Ted Sears', 'Richard Creedon', 'Otto England...","['Adriana Caselotti', 'Lucille La Verne', 'Har...","['Frank Churchill', 'Paul Smith', 'Leigh Harli...",RKO Radio Pictures,$1.49 million,$418 million,NaN
2,Pinocchio,Walt Disney Productions,"['February 7, 1940 ( Center Theatre )', 'Febru...",88 minutes,United States,88.0,2600000.0,164000000.0,1940-02-07,7.4,...,100%,"['Ben Sharpsteen', 'Hamilton Luske', 'Bill Rob...",Walt Disney,NaN,"['Cliff Edwards', 'Dickie Jones', 'Christian R...","['Leigh Harline', 'Paul J. Smith']",RKO Radio Pictures,$2.6 million,$164 million,NaN
3,Fantasia,Walt Disney Productions,"['November 13, 1940']",126 minutes,United States,126.0,2280000.0,83300000.0,1940-11-13,7.8,...,95%,"['Samuel Armstrong', 'James Algar', 'Bill Robe...","['Walt Disney', 'Ben Sharpsteen']",NaN,"['Leopold Stokowski', 'Deems Taylor']",See program,"['Walt Disney Productions', 'RKO Radio Pictures']",$2.28 million,$76.4–$83.3 million,NaN
4,The Reluctant Dragon,Walt Disney Productions,"['June 20, 1941']",74 minutes,United States,74.0,600000.0,960000.0,1941-06-20,6.9,...,67%,"['Alfred Werker', '(live action)', 'Hamilton L...",Walt Disney,"['Live-action:', 'Ted Sears', 'Al Perkins', 'L...","['Robert Benchley', 'Frances Gifford', 'Buddy ...","['Frank Churchill', 'Larry Morey']",RKO Radio Pictures,"$600,000","$960,000 (worldwide rentals)",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Soul,"['Walt Disney Pictures', 'Pixar Animation Stud...","['October 15, 2020 ( Rome Film Festival )', 'N...",NaN,United States,NaN,150000000.0,NaN,2020-10-15,7.0,...,45%,Pete Docter,Dana Murray,NaN,"['Jamie Foxx', 'Tina Fey', 'Questlove', 'Phyli...","['Trent Reznor', 'Atticus Ross']","['Walt Disney Studios', 'Motion Pictures']",$150 million+,NaN,NaN
428,Raya and the Last Dragon,"['Walt Disney Pictures', 'Walt Disney Animatio...","['March 12, 2021']",NaN,United States,NaN,NaN,NaN,2021-03-12,NaN,...,NaN,"['Don Hall', 'Carlos López Estrada']","['Osnat Shurer', 'Peter Del Vecho']","['Qui Nguyen', 'Adele Lim']","['Kelly Marie Tran', 'Awkwafina']",NaN,"['Walt Disney Studios', 'Motion Pictures']",NaN,NaN,NaN
429,Cruella,"['Walt Disney Pictures', 'Gunn Films', 'Marc P...","['May 28, 2021 (United States)']",NaN,United States,NaN,NaN,NaN,2021-05-28,NaN,...,NaN,Craig Gillespie,"['Kristin Burr', 'Andrew Gunn', 'Marc Platt']",NaN,"['Emma Stone', 'Emma Thompson', 'Paul Walter H...",NaN,Walt Disney Studios Motion Pictures,NaN,NaN,NaN
430,Jungle Cruise,"['Walt Disney Pictures', 'Davis Entertainment'...","['July 30, 2021 (United States)']",NaN,United States,NaN,NaN,NaN,2021-07-30,NaN,...,NaN,Jaume Collet-Serra,"['John Davis', 'John Fox', 'Beau Flynn', 'Dway...",NaN,"['Dwayne Johnson', 'Emily Blunt', 'Édgar Ramír...","['James Newton Howard', 'Metallica']",Walt Disney Studios Motion Pictures,NaN,NaN,NaN
431,The Beatles: Get Back,NaN,['27 August 2021'],NaN,"['United Kingdom', 'New Zealand', 'United Stat...",NaN,NaN,NaN,2021-08-27,8.0,...,NaN,Peter Jackson,"['Peter Jackson', 'Clare Olssen', 'Jonathan Cl...",NaN,The Beatles,The Beatles,"['Walt Disney Studios', 'Motion Pictures']",NaN,NaN,"['Walt Disney Pictures', 'Apple Corps', 'WingN..."

In [64]:
disneylist = pd.read_csv('data/fulltitlelist2.csv')
disneylist

     Unnamed: 0                                                  0
0             0    \n1.\nSnow White and the Seven Dwarfs\n(1937)\n
1             1                          \n2.\nPinocchio\n(1940)\n
2             2                           \n3.\nFantasia\n(1940)\n
3             3           \n4.\nThe Reluctant Dragon\n(I) (1941)\n
4             4                              \n5.\nDumbo\n(1941)\n
..          ...                                                ...
524         524         \n525.\nBeauty and the Beast\n(I) (2017)\n
525         525  \n526.\nPirates of the Caribbean: Dead Men Tel...
526         526                           \n527.\nCars 3\n(2017)\n
527         527                    \n528.\nIncredibles 2\n(2018)\n
528         528                      \n529.\nToy Story 4\n(2019)\n

[529 rows x 2 columns]

In [65]:
disneytotal.sort_values('release_date')

,movie_title,release_date,genre,mpaa_rating,total_gross,inflation_adjusted_gross
0,Snow White and the Seven Dwarfs,1937-12-21,Musical,G,184925485,5228953251
1,Pinocchio,1940-02-09,Adventure,G,84300000,2188229052
2,Fantasia,1940-11-13,Musical,G,83320000,2187090808
3,Song of the South,1946-11-12,Adventure,G,65000000,1078510579
4,Cinderella,1950-02-15,Drama,G,85000000,920608730
...,...,...,...,...,...,...
574,The Light Between Oceans,2016-09-02,Drama,PG-13,12545979,12545979
575,Queen of Katwe,2016-09-23,Drama,PG,8874389,8874389
576,Doctor Strange,2016-11-04,Adventure,PG-13,232532923,232532923
577,Moana,2016-11-23,Adventure,PG,246082029,246082029
578,Rogue One: A Star Wars Story,2016-12-16,Adventure,PG-13,529483936,529483936

In [66]:
disneymovies_total = pd.merge(disneymovies, disneytotal, 
                               left_on = 'title', right_on = 'movie_title', 
                               how = 'outer')
disneymovies_total

,title,Production company,Release date,Running time,Country,Running time (int),Budget (float),Box office (float),Release date (datetime),imdb,...,Distributed by,Budget,Box office,Production companies,movie_title,release_date,genre,mpaa_rating,total_gross,inflation_adjusted_gross
0,Academy Award Review of,Walt Disney Productions,"['May 19, 1937']",41 minutes (74 minutes 1966 release),United States,41.0,NaN,NaN,1937-05-19,7.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Snow White and the Seven Dwarfs,Walt Disney Productions,"['December 21, 1937 ( Carthay Circle Theatre ,...",83 minutes,United States,83.0,1490000.0,418000000.0,1937-12-21,7.6,...,RKO Radio Pictures,$1.49 million,$418 million,NaN,Snow White and the Seven Dwarfs,1937-12-21,Musical,G,184925485.0,5.228953e+09
2,Pinocchio,Walt Disney Productions,"['February 7, 1940 ( Center Theatre )', 'Febru...",88 minutes,United States,88.0,2600000.0,164000000.0,1940-02-07,7.4,...,RKO Radio Pictures,$2.6 million,$164 million,NaN,Pinocchio,1940-02-09,Adventure,G,84300000.0,2.188229e+09
3,Fantasia,Walt Disney Productions,"['November 13, 1940']",126 minutes,United States,126.0,2280000.0,83300000.0,1940-11-13,7.8,...,"['Walt Disney Productions', 'RKO Radio Pictures']",$2.28 million,$76.4–$83.3 million,NaN,Fantasia,1940-11-13,Musical,G,83320000.0,2.187091e+09
4,The Reluctant Dragon,Walt Disney Productions,"['June 20, 1941']",74 minutes,United States,74.0,600000.0,960000.0,1941-06-20,6.9,...,RKO Radio Pictures,"$600,000","$960,000 (worldwide rentals)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Captain America: Civil War,2016-05-06,Action,PG-13,408084349.0,4.080843e+08
798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Pete’s Dragon,2016-08-12,Adventure,PG,76233151.0,7.623315e+07
799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,The Light Between Oceans,2016-09-02,Drama,PG-13,12545979.0,1.254598e+07
800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Doctor Strange,2016-11-04,Adventure,PG-13,232532923.0,2.325329e+08
801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Rogue One: A Star Wars Story,2016-12-16,Adventure,PG-13,529483936.0,5.294839e+08

In [67]:
disneymovies_total.loc[disneymovies_total['title'] == 'The Lion King']

,title,Production company,Release date,Running time,Country,Running time (int),Budget (float),Box office (float),Release date (datetime),imdb,...,Distributed by,Budget,Box office,Production companies,movie_title,release_date,genre,mpaa_rating,total_gross,inflation_adjusted_gross
212,The Lion King,"['Walt Disney Pictures', 'Walt Disney Feature ...","['June 15, 1994', 'June 24, 1994']",88 minutes,United States,88.0,45000000.0,9.685000e+08,1994-06-15,8.5,...,Buena Vista Pictures,$45 million,$968.5 million,NaN,The Lion King,1994-06-15,Adventure,G,422780140.0,761640898.0
213,The Lion King,"['Walt Disney Pictures', 'Fairview Entertainme...","['July 9, 2019 ( Hollywood )', 'July 19, 2019 ...",118 minutes,United States,118.0,250000000.0,1.657000e+09,2019-07-09,8.5,...,"['Walt Disney Studios', 'Motion Pictures']",$250–260 million,$1.657 billion,NaN,The Lion King,1994-06-15,Adventure,G,422780140.0,761640898.0

In [68]:
disney_mylist = pd.read_csv('data/disney_mylist2.csv')
disney_mylist

,Rank,Release,To Date,Release Date,Max Theaters,Days,Opening,Open Th
0,1.0,Star Wars: Episode VII - The Force Awakens,"$936,662,225",18-Dec-15,"4,134",167,"$247,966,675","4,134"
1,2.0,Avengers: Endgame,"$858,373,000",26-Apr-19,"4,662",139,"$357,115,007","4,662"
2,3.0,Black Panther,"$700,059,566",16-Feb-18,"4,084",174,"$202,003,951","4,020"
3,4.0,Avengers: Infinity War,"$678,815,482",27-Apr-18,"4,474",139,"$257,698,183","4,474"
4,5.0,The Avengers,"$623,357,910",4-May-12,"4,349",153,"$207,438,708","4,349"
...,...,...,...,...,...,...,...,...
627,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-
628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-
629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-
630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-
631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-

In [69]:
disney_mylist.tail(50)

,Rank,Release,To Date,Release Date,Max Theaters,Days,Opening,Open Th
582,632.0,A Simple Twist of Fate,"$3,430,583",2-Sep-94,319,-,"$1,404,904",NaN
583,633.0,Father Hood,"$3,418,141",27-Aug-93,643,-,"$1,286,806",582
584,634.0,Squanto: A Warrior's Tale,"$3,342,223",28-Oct-94,"1,022",-,"$1,119,016",693
585,635.0,My Boyfriend's Back,"$3,335,984",6-Aug-93,"1,165",-,"$1,465,476",302
586,636.0,The Fifth Estate,"$3,255,008",18-Oct-13,"1,769",48,"$1,673,351",593
587,637.0,Blame It on the Bellboy,"$3,104,545",6-Mar-92,462,-,"$1,326,472","1,275"
588,638.0,Running Brave,"$3,000,000",4-Nov-83,440,-,"$441,145",319
589,639.0,Cradle Will Rock,"$2,903,404",10-Dec-99,506,-,"$93,998",643
590,640.0,Midnight Madness,"$2,900,000",8-Feb-80,-,-,-,"1,022"
591,641.0,Newsies,"$2,819,485",10-Apr-92,"1,259",-,"$1,232,508","1,165"
592,643.0,Jefferson in Paris,"$2,473,668",31-Mar-95,351,97,"$61,349","1,769"
593,644.0,Shadow Conspiracy,"$2,312,463",31-Jan-97,837,-,"$1,370,831",462
594,646.0,Noises Off...,"$2,280,148",20-Mar-92,451,-,"$981,452",234
595,647.0,Washington Square,"$1,851,761",5-Oct-97,35,193,"$14,352",8
596,648.0,Gun Shy,"$1,638,202",4-Feb-00,296,-,"$703,109",-
597,649.0,Veronica Guerin,"$1,571,504",17-Oct-03,472,48,"$611,276","1,223"
598,650.0,X Games 3D: The Movie,"$1,391,434",21-Aug-09,"1,399",13,"$837,216",NaN
599,652.0,Two Much,"$1,141,556",15-Mar-96,348,-,"$592,871",837
600,654.0,Sacred Planet,"$1,108,356",22-Apr-04,18,-,-,451
601,655.0,Where the Heart Is,"$1,106,475",23-Feb-90,235,-,"$530,893",1
602,656.0,Money for Nothing,"$1,039,824",10-Sep-93,449,-,"$491,206",296
603,659.0,Firelight,"$785,482",4-Sep-98,39,118,"$135,401",NaN
604,662.0,Holy Matrimony,"$713,234",8-Apr-94,-,-,-,NaN
605,664.0,Prefontaine,"$589,304",24-Jan-97,201,-,"$311,253",NaN
606,666.0,Funny Bones,"$532,268",24-Mar-95,49,104,"$26,946",NaN
607,667.0,Boys,"$516,349",10-May-96,328,20,"$270,107",NaN
608,668.0,Crossing the Bridge,"$479,676",11-Sep-92,235,-,"$243,695",NaN
609,669.0,The Last Shot,"$464,275",24-Sep-04,40,55,"$164,801",NaN
610,672.0,A Pyromaniac's Love Story,"$345,972",28-Apr-95,379,-,"$268,932",NaN
611,675.0,America's Heart & Soul,"$314,402",2-Jul-04,98,27,"$134,939",NaN
612,677.0,Feast of July,"$293,274",13-Oct-95,47,48,"$22,818",NaN
613,678.0,Morning Light,"$275,497",17-Oct-08,55,39,"$129,295",379
614,679.0,High Heels and Low Lifes,"$228,194",26-Oct-01,175,20,"$113,512",NaN
615,681.0,Breakfast of Champions,"$178,278",17-Sep-99,11,97,"$42,326",NaN
616,682.0,Endurance,"$137,124",14-May-99,20,-,"$14,339",NaN
617,685.0,Waking Sleeping Beauty,"$80,741",26-Mar-10,5,41,"$33,115",175
618,687.0,It's Pat: The Movie,"$60,822",26-Aug-94,33,-,"$31,370",7
619,688.0,The Boys,"$55,513",22-May-09,5,111,"$14,632",4
620,690.0,An Alan Smithee Film: Burn Hollywood Burn,"$45,779",27-Feb-98,19,13,"$28,992",NaN
621,691.0,The War at Home,"$44,722",22-Nov-96,6,-,"$15,040",NaN
622,692.0,Century of Cinema: A Personal Journey with Mar...,"$39,075",6-Mar-98,1,20,"$10,350",NaN
623,693.0,Walt & El Grupo,"$20,521",9-Sep-09,4,57,"$6,059",5
624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
627,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-
628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-
629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-
630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-
631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-

In [70]:
disney_mylist=disney_mylist.drop(disney_mylist.index[624:])
disney_mylist

,Rank,Release,To Date,Release Date,Max Theaters,Days,Opening,Open Th
0,1.0,Star Wars: Episode VII - The Force Awakens,"$936,662,225",18-Dec-15,"4,134",167,"$247,966,675","4,134"
1,2.0,Avengers: Endgame,"$858,373,000",26-Apr-19,"4,662",139,"$357,115,007","4,662"
2,3.0,Black Panther,"$700,059,566",16-Feb-18,"4,084",174,"$202,003,951","4,020"
3,4.0,Avengers: Infinity War,"$678,815,482",27-Apr-18,"4,474",139,"$257,698,183","4,474"
4,5.0,The Avengers,"$623,357,910",4-May-12,"4,349",153,"$207,438,708","4,349"
...,...,...,...,...,...,...,...,...
619,688.0,The Boys,"$55,513",22-May-09,5,111,"$14,632",4
620,690.0,An Alan Smithee Film: Burn Hollywood Burn,"$45,779",27-Feb-98,19,13,"$28,992",NaN
621,691.0,The War at Home,"$44,722",22-Nov-96,6,-,"$15,040",NaN
622,692.0,Century of Cinema: A Personal Journey with Mar...,"$39,075",6-Mar-98,1,20,"$10,350",NaN
623,693.0,Walt & El Grupo,"$20,521",9-Sep-09,4,57,"$6,059",5

In [71]:
disney_mylist=disney_mylist.drop(['Rank'], axis=1)
disney_mylist

,Release,To Date,Release Date,Max Theaters,Days,Opening,Open Th
0,Star Wars: Episode VII - The Force Awakens,"$936,662,225",18-Dec-15,"4,134",167,"$247,966,675","4,134"
1,Avengers: Endgame,"$858,373,000",26-Apr-19,"4,662",139,"$357,115,007","4,662"
2,Black Panther,"$700,059,566",16-Feb-18,"4,084",174,"$202,003,951","4,020"
3,Avengers: Infinity War,"$678,815,482",27-Apr-18,"4,474",139,"$257,698,183","4,474"
4,The Avengers,"$623,357,910",4-May-12,"4,349",153,"$207,438,708","4,349"
...,...,...,...,...,...,...,...
619,The Boys,"$55,513",22-May-09,5,111,"$14,632",4
620,An Alan Smithee Film: Burn Hollywood Burn,"$45,779",27-Feb-98,19,13,"$28,992",NaN
621,The War at Home,"$44,722",22-Nov-96,6,-,"$15,040",NaN
622,Century of Cinema: A Personal Journey with Mar...,"$39,075",6-Mar-98,1,20,"$10,350",NaN
623,Walt & El Grupo,"$20,521",9-Sep-09,4,57,"$6,059",5

In [72]:
disney_mylist.loc[disney_mylist['Release'] == 'The Lion King']

,Release,To Date,Release Date,Max Theaters,Days,Opening,Open Th
7,The Lion King,"$543,638,043",19-Jul-19,"4,802",139,"$191,770,759","4,725"
34,The Lion King,"$312,855,561",15-Jun-94,"2,624",-,"$1,586,753",2

In [73]:
lmpssa

,Rank,Release,Lifetime Gross,Max Theaters,Opening,Open Th,Release Date,Distributor,Estimated,category
0,1,The Lion King,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
1,2,Beauty and the Beast,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,False,live reimaginings
2,3,The Jungle Book,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,False,live reimaginings
3,4,Aladdin,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,False,live reimaginings
4,5,Alice in Wonderland,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,False,live reimaginings
...,...,...,...,...,...,...,...,...,...,...
101,10,The Princess and the Frog,"$104,400,899",3475,"$786,190",2,"Nov 25, 2009",Walt Disney Studios Motion Pictures,False,animated
102,11,Meet the Robinsons,"$97,822,171",3435,"$25,123,781",3413,"Mar 30, 2007",Walt Disney Studios Motion Pictures,False,animated
103,12,Encanto,"$96,093,622",3980,"$27,206,494",3980,"Nov 24, 2021",Walt Disney Studios Motion Pictures,False,animated
104,13,Raya and the Last Dragon,"$54,723,032",2375,"$8,502,498",2045,"Mar 5, 2021",Walt Disney Studios Motion Pictures,False,animated
105,14,Winnie the Pooh,"$26,692,846",2405,"$7,857,076",2405,"Jul 15, 2011",Walt Disney Studios Motion Pictures,False,animated

In [74]:
disney_mylist_lmpssa = pd.merge(disney_mylist, lmpssa, 
                               left_on = 'Release', right_on = 'Release', 
                               how = 'outer')
disney_mylist_lmpssa

,Release,To Date,Release Date_x,Max Theaters_x,Days,Opening_x,Open Th_x,Rank,Lifetime Gross,Max Theaters_y,Opening_y,Open Th_y,Release Date_y,Distributor,Estimated,category
0,Star Wars: Episode VII - The Force Awakens,"$936,662,225",18-Dec-15,"4,134",167,"$247,966,675","4,134",1,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,False,starwars
1,Avengers: Endgame,"$858,373,000",26-Apr-19,"4,662",139,"$357,115,007","4,662",1,"$858,373,000",4662,"$357,115,007",4662,"Apr 26, 2019",Walt Disney Studios Motion Pictures,False,marvel
2,Black Panther,"$700,059,566",16-Feb-18,"4,084",174,"$202,003,951","4,020",3,"$700,059,566",4084,"$202,003,951",4020,"Feb 16, 2018",Walt Disney Studios Motion Pictures,False,marvel
3,Avengers: Infinity War,"$678,815,482",27-Apr-18,"4,474",139,"$257,698,183","4,474",4,"$678,815,482",4474,"$257,698,183",4474,"Apr 27, 2018",Walt Disney Studios Motion Pictures,False,marvel
4,The Avengers,"$623,357,910",4-May-12,"4,349",153,"$207,438,708","4,349",5,"$623,357,910",4349,"$207,438,708",4349,"May 4, 2012",Walt Disney Studios Motion Pictures,False,marvel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,Star Wars: Episode IV - A New Hope,NaN,NaN,NaN,NaN,NaN,NaN,7,"$307,263,857",1750,"$1,554,475",43,"May 25, 1977",Twentieth Century Fox,False,starwars
648,Star Wars: Episode II - Attack of the Clones,NaN,NaN,NaN,NaN,NaN,NaN,8,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,False,starwars
649,Star Wars: Episode VI - Return of the Jedi,NaN,NaN,NaN,NaN,NaN,NaN,9,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,False,starwars
650,Star Wars: Episode V - The Empire Strikes Back,NaN,NaN,NaN,NaN,NaN,NaN,11,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,False,starwars
651,Star Wars: The Clone Wars,NaN,NaN,NaN,NaN,NaN,NaN,16,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,False,starwars

In [75]:
disney_mylist_lmpssa=disney_mylist_lmpssa.drop(['Estimated'], axis=1)
disney_mylist_lmpssa

,Release,To Date,Release Date_x,Max Theaters_x,Days,Opening_x,Open Th_x,Rank,Lifetime Gross,Max Theaters_y,Opening_y,Open Th_y,Release Date_y,Distributor,category
0,Star Wars: Episode VII - The Force Awakens,"$936,662,225",18-Dec-15,"4,134",167,"$247,966,675","4,134",1,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,starwars
1,Avengers: Endgame,"$858,373,000",26-Apr-19,"4,662",139,"$357,115,007","4,662",1,"$858,373,000",4662,"$357,115,007",4662,"Apr 26, 2019",Walt Disney Studios Motion Pictures,marvel
2,Black Panther,"$700,059,566",16-Feb-18,"4,084",174,"$202,003,951","4,020",3,"$700,059,566",4084,"$202,003,951",4020,"Feb 16, 2018",Walt Disney Studios Motion Pictures,marvel
3,Avengers: Infinity War,"$678,815,482",27-Apr-18,"4,474",139,"$257,698,183","4,474",4,"$678,815,482",4474,"$257,698,183",4474,"Apr 27, 2018",Walt Disney Studios Motion Pictures,marvel
4,The Avengers,"$623,357,910",4-May-12,"4,349",153,"$207,438,708","4,349",5,"$623,357,910",4349,"$207,438,708",4349,"May 4, 2012",Walt Disney Studios Motion Pictures,marvel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,Star Wars: Episode IV - A New Hope,NaN,NaN,NaN,NaN,NaN,NaN,7,"$307,263,857",1750,"$1,554,475",43,"May 25, 1977",Twentieth Century Fox,starwars
648,Star Wars: Episode II - Attack of the Clones,NaN,NaN,NaN,NaN,NaN,NaN,8,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,starwars
649,Star Wars: Episode VI - Return of the Jedi,NaN,NaN,NaN,NaN,NaN,NaN,9,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,starwars
650,Star Wars: Episode V - The Empire Strikes Back,NaN,NaN,NaN,NaN,NaN,NaN,11,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,starwars
651,Star Wars: The Clone Wars,NaN,NaN,NaN,NaN,NaN,NaN,16,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,starwars

In [76]:
disney_mylist_lmpssa.loc[disney_mylist_lmpssa['category'] == 'starwars']

,Release,To Date,Release Date_x,Max Theaters_x,Days,Opening_x,Open Th_x,Rank,Lifetime Gross,Max Theaters_y,Opening_y,Open Th_y,Release Date_y,Distributor,category
0,Star Wars: Episode VII - The Force Awakens,"$936,662,225",18-Dec-15,"4,134",167,"$247,966,675","4,134",1,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,starwars
5,Star Wars: Episode VIII - The Last Jedi,"$620,181,382",15-Dec-17,"4,232",125,"$220,009,584","4,232",2,"$620,181,382",4232,"$220,009,584",4232,"Dec 15, 2017",Walt Disney Studios Motion Pictures,starwars
9,Rogue One: A Star Wars Story,"$532,177,324",16-Dec-16,"4,157",139,"$155,081,681","4,157",3,"$532,177,324",4157,"$155,081,681",4157,"Dec 16, 2016",Walt Disney Studios Motion Pictures,starwars
10,Star Wars: Episode IX - The Rise of Skywalker,"$515,202,542",20-Dec-19,"4,406",-,"$177,383,864","4,406",4,"$515,202,542",4406,"$177,383,864",4406,"Dec 20, 2019",Walt Disney Studios Motion Pictures,starwars
68,Solo: A Star Wars Story,"$213,767,512",25-May-18,"4,381",118,"$84,420,489","4,381",10,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,starwars
645,Star Wars: Episode I - The Phantom Menace,NaN,NaN,NaN,NaN,NaN,NaN,5,"$431,088,295",3126,"$64,820,970",2970,"May 19, 1999",Twentieth Century Fox,starwars
646,Star Wars: Episode III - Revenge of the Sith,NaN,NaN,NaN,NaN,NaN,NaN,6,"$380,270,577",3663,"$108,435,841",3661,"May 19, 2005",Twentieth Century Fox,starwars
647,Star Wars: Episode IV - A New Hope,NaN,NaN,NaN,NaN,NaN,NaN,7,"$307,263,857",1750,"$1,554,475",43,"May 25, 1977",Twentieth Century Fox,starwars
648,Star Wars: Episode II - Attack of the Clones,NaN,NaN,NaN,NaN,NaN,NaN,8,"$302,191,252",3161,"$80,027,814",3161,"May 16, 2002",Twentieth Century Fox,starwars
649,Star Wars: Episode VI - Return of the Jedi,NaN,NaN,NaN,NaN,NaN,NaN,9,"$252,583,617",1764,"$23,019,618",1002,"May 25, 1983",Twentieth Century Fox,starwars
650,Star Wars: Episode V - The Empire Strikes Back,NaN,NaN,NaN,NaN,NaN,NaN,11,"$209,398,025",1278,"$4,910,483",126,"May 21, 1980",Twentieth Century Fox,starwars
651,Star Wars: The Clone Wars,NaN,NaN,NaN,NaN,NaN,NaN,16,"$35,161,554",3452,"$14,611,273",3452,"Aug 15, 2008",Warner Bros.,starwars

In [77]:
disney_mylist_lmpssa.loc[disney_mylist_lmpssa['category'].isnull()]

,Release,To Date,Release Date_x,Max Theaters_x,Days,Opening_x,Open Th_x,Rank,Lifetime Gross,Max Theaters_y,Opening_y,Open Th_y,Release Date_y,Distributor,category
19,Pirates of the Caribbean: Dead Man's Chest,"$423,315,812",7-Jul-06,"4,133",153,"$135,634,554","4,133",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Pirates of the Caribbean: At World's End,"$309,420,425",25-May-07,"4,362",132,"$114,732,820","4,362",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Pirates of the Caribbean: The Curse of the Bla...,"$305,413,918",9-Jul-03,"3,416",183,"$46,630,690","3,269",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,The Little Mermaid,"$296,989,468",26-May-23,"4,320",-,"$95,578,040","4,320",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,The Little Mermaid,"$84,355,863",17-Nov-89,"1,533",-,"$6,031,914",994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
622,The Boys,"$55,513",22-May-09,5,111,"$14,632",4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
623,An Alan Smithee Film: Burn Hollywood Burn,"$45,779",27-Feb-98,19,13,"$28,992",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
624,The War at Home,"$44,722",22-Nov-96,6,-,"$15,040",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,Century of Cinema: A Personal Journey with Mar...,"$39,075",6-Mar-98,1,20,"$10,350",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
626,Walt & El Grupo,"$20,521",9-Sep-09,4,57,"$6,059",5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
disney_mylist_lmpssa.to_csv()

',Release,To Date,Release Date_x,Max Theaters_x,Days,Opening_x,Open Th_x,Rank,Lifetime Gross,Max Theaters_y,Opening_y,Open Th_y,Release Date_y,Distributor,category\r\n0,Star Wars: Episode VII - The Force Awakens,"$936,662,225 ",18-Dec-15,"4,134",167,"$247,966,675 ","4,134",1,"$936,662,225",4134,"$247,966,675",4134,"Dec 18, 2015",Walt Disney Studios Motion Pictures,starwars\r\n1,Avengers: Endgame,"$858,373,000 ",26-Apr-19,"4,662",139,"$357,115,007 ","4,662",1,"$858,373,000",4662,"$357,115,007",4662,"Apr 26, 2019",Walt Disney Studios Motion Pictures,marvel\r\n2,Black Panther,"$700,059,566 ",16-Feb-18,"4,084",174,"$202,003,951 ","4,020",3,"$700,059,566",4084,"$202,003,951",4020,"Feb 16, 2018",Walt Disney Studios Motion Pictures,marvel\r\n3,Avengers: Infinity War,"$678,815,482 ",27-Apr-18,"4,474",139,"$257,698,183 ","4,474",4,"$678,815,482",4474,"$257,698,183",4474,"Apr 27, 2018",Walt Disney Studios Motion Pictures,marvel\r\n4,The Avengers,"$623,357,910 ",4-May-12,"4,349",153,"$207,438,708 ","4,349",5,"$623,357,910",4349,"$207,438,708",4349,"May 4, 2012",Walt Disney Studios Motion Pictures,marvel\r\n5,Star Wars: Episode VIII - The Last Jedi,"$620,181,382 ",15-Dec-17,"4,232",125,"$220,009,584 ","4,232",2,"$620,181,382",4232,"$220,009,584",4232,"Dec 15, 2017",Walt Disney Studios Motion Pictures,starwars\r\n6,Incredibles 2,"$608,581,744 ",15-Jun-18,"4,410",181,"$182,687,905 ","4,410",1,"$608,581,744",4410,"$182,687,905",4410,"Jun 15, 2018",Walt Disney Studios Motion Pictures,pixar\r\n7,The Lion King,"$543,638,043 ",19-Jul-19,"4,802",139,"$191,770,759 ","4,725",1,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,live reimaginings\r\n8,The Lion King,"$312,855,561 ",15-Jun-94,"2,624",-,"$1,586,753 ",2,1,"$543,638,043",4802,"$191,770,759",4725,"Jul 19, 2019",Walt Disney Studios Motion Pictures,live reimaginings\r\n9,Rogue One: A Star Wars Story,"$532,177,324 ",16-Dec-16,"4,157",139,"$155,081,681 ","4,157",3,"$532,177,324",4157,"$155,081,681",4157,"Dec 16, 2016",Walt Disney Studios Motion Pictures,starwars\r\n10,Star Wars: Episode IX - The Rise of Skywalker,"$515,202,542 ",20-Dec-19,"4,406",-,"$177,383,864 ","4,406",4,"$515,202,542",4406,"$177,383,864",4406,"Dec 20, 2019",Walt Disney Studios Motion Pictures,starwars\r\n11,Beauty and the Beast,"$504,014,165 ",17-Mar-17,"4,210",118,"$174,750,616 ","4,210",2,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,live reimaginings\r\n12,Beauty and the Beast,"$145,863,363 ",15-Nov-91,"1,960",-,"$162,146 ",2,2,"$504,014,165",4210,"$174,750,616",4210,"Mar 17, 2017",Walt Disney Studios Motion Pictures,live reimaginings\r\n13,Finding Dory,"$486,295,561 ",17-Jun-16,"4,305",174,"$135,060,273 ","4,305",2,"$486,295,561",4305,"$135,060,273",4305,"Jun 17, 2016",Walt Disney Studios Motion Pictures,pixar\r\n14,Frozen II,"$477,373,578 ",22-Nov-19,"4,440",-,"$130,263,358 ","4,440",1,"$477,373,578",4440,"$130,263,358",4440,"Nov 22, 2019",Walt Disney Studios Motion Pictures,animated\r\n15,Avengers: Age of Ultron,"$459,005,868 ",1-May-15,"4,276",160,"$191,271,109 ","4,276",6,"$459,005,868",4276,"$191,271,109",4276,"May 1, 2015",Walt Disney Studios Motion Pictures,marvel\r\n16,Black Panther: Wakanda Forever,"$453,829,060 ",11-Nov-22,"4,396",125,"$181,339,761 ","4,396",7,"$453,829,060",4396,"$181,339,761",4396,"Nov 11, 2022",Walt Disney Studios Motion Pictures,marvel\r\n17,Toy Story 4,"$434,038,008 ",21-Jun-19,"4,575",167,"$120,908,065 ","4,575",3,"$434,038,008",4575,"$120,908,065",4575,"Jun 21, 2019",Walt Disney Studios Motion Pictures,pixar\r\n18,Captain Marvel,"$426,829,839 ",8-Mar-19,"4,310",118,"$153,433,423 ","4,310",8,"$426,829,839",4310,"$153,433,423",4310,"Mar 8, 2019",Walt Disney Studios Motion Pictures,marvel\r\n19,Pirates of the Caribbean: Dead Man\'s Chest,"$423,315,812 ",7-Jul-06,"4,133",153,"$135,634,554 ","4,133",,,,,,,,\r\n20,Toy Story 3,"$415,004,880 ",18-Jun-10,"4,028",167,"$110,307,189 ","4,028",4,"$415,004,880",4028,"$110,307,189",4028,"Jun 18, 2010",Walt Disney Studios Motion Pictures,pixar\r\n21,Doctor Strange in the Multiverse of Madness,"$411,331,607 ",6-May-22,"4,534",-,"$187,420,998 ","4,534",9,"$411,331,607",4534,"$187,420,998",4534,"May 6, 2022",Walt Disney Studios Motion Pictures,marvel\r\n22,Iron Man 3,"$409,013,994 ",3-May-13,"4,253",132,"$174,144,585 ","4,253",10,"$409,013,994",4253,"$174,144,585",4253,"May 3, 2013",Walt Disney Studios Motion Pictures,marvel\r\n23,Captain America: Civil War,"$408,084,349 ",6-May-16,"4,226",139,"$179,139,142 ","4,226",11,"$408,084,349",4226,"$179,139,142",4226,"May 6, 2016",Walt Disney Studios Motion Pictures,marvel\r\n24,Frozen,"$400,738,009 ",22-Nov-13,"3,742",237,"$243,390 ",1,2,"$400,738,009",3742,"$243,390",1,"Nov 22, 2013",Walt Disney Studios Motion Pictures,animated\r\n25,Guardians of the Galaxy Vol. 2,"$389,813,101 ",5-May-17,"4,347",139,"$146,510,104 ","4,347",13,"$389,813,101",4347,"$146,510,104",4347,"May 5, 2017",Walt Disney Studios Motion Pictures,marvel\r\n26,The Jungle Book,"$364,001,123 ",15-Apr-16,"4,144",167,"$103,261,464 ","4,028",3,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,live reimaginings\r\n27,The Jungle Book,"$364,001,123 ",15-Apr-16,"4,144",167,"$103,261,464 ","4,028",16,"$43,229,904",2012,"$5,129,959",1880,"Dec 25, 1994",Walt Disney Studios Motion Pictures,live reimaginings\r\n28,The Jungle Book,"$73,741,048 ",18-Oct-67,-,-,-,-,3,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,live reimaginings\r\n29,The Jungle Book,"$73,741,048 ",18-Oct-67,-,-,-,-,16,"$43,229,904",2012,"$5,129,959",1880,"Dec 25, 1994",Walt Disney Studios Motion Pictures,live reimaginings\r\n30,The Jungle Book,"$43,229,904 ",25-Dec-94,"2,012",-,"$5,129,959 ","1,880",3,"$364,001,123",4144,"$103,261,464",4028,"Apr 15, 2016",Walt Disney Studios Motion Pictures,live reimaginings\r\n31,The Jungle Book,"$43,229,904 ",25-Dec-94,"2,012",-,"$5,129,959 ","1,880",16,"$43,229,904",2012,"$5,129,959",1880,"Dec 25, 1994",Walt Disney Studios Motion Pictures,live reimaginings\r\n32,Guardians of the Galaxy Vol. 3,"$358,960,411 ",5-May-23,"4,450",-,"$118,414,021 ","4,450",14,"$356,577,614",4450,"$118,414,021",4450,"May 5, 2023",Walt Disney Studios Motion Pictures,marvel\r\n33,Inside Out,"$356,461,711 ",19-Jun-15,"4,158",174,"$90,440,272 ","3,946",5,"$356,461,711",4158,"$90,440,272",3946,"Jun 19, 2015",Walt Disney Studios Motion Pictures,pixar\r\n34,Aladdin,"$355,559,216 ",24-May-19,"4,476",153,"$91,500,929 ","4,476",4,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,live reimaginings\r\n35,Aladdin,"$217,350,219 ",13-Nov-92,"2,331",-,"$196,664 ",2,4,"$355,559,216",4476,"$91,500,929",4476,"May 24, 2019",Walt Disney Studios Motion Pictures,live reimaginings\r\n36,Thor: Love and Thunder,"$343,256,830 ",8-Jul-22,"4,375",98,"$144,165,107 ","4,375",15,"$343,256,830",4375,"$144,165,107",4375,"Jul 8, 2022",Walt Disney Studios Motion Pictures,marvel\r\n37,Zootopia,"$341,268,248 ",4-Mar-16,"3,959",153,"$75,063,401 ","3,827",3,"$341,268,248",3959,"$75,063,401",3827,"Mar 4, 2016",Walt Disney Studios Motion Pictures,animated\r\n38,Finding Nemo,"$339,714,978 ",30-May-03,"3,425",202,"$70,251,710 ","3,374",6,"$339,714,978",3425,"$70,251,710",3374,"May 30, 2003",Walt Disney Studios Motion Pictures,pixar\r\n39,Alice in Wonderland,"$334,191,110 ",5-Mar-10,"3,739",125,"$116,101,023 ","3,728",5,"$334,191,110",3739,"$116,101,023",3728,"Mar 5, 2010",Walt Disney Studios Motion Pictures,live reimaginings\r\n40,Guardians of the Galaxy,"$333,176,600 ",1-Aug-14,"4,088",174,"$94,320,883 ","4,080",17,"$333,176,600",4088,"$94,320,883",4080,"Aug 1, 2014",Walt Disney Studios Motion Pictures,marvel\r\n41,Thor: Ragnarok,"$315,058,289 ",3-Nov-17,"4,080",132,"$122,744,989 ","4,080",19,"$315,058,289",4080,"$122,744,989",4080,"Nov 3, 2017",Walt Disney Studios Motion Pictures,marvel\r\n42,Pirates of the Caribbean: At World\'s End,"$309,420,425 ",25-May-07,"4,362",132,"$114,732,820 ","4,362",,,,,,,,\r\n43,Pirates of the Caribbean: The Curse of the Black Pearl,"$305,413,918 ",9-Jul-03,"3,416",183,"$46,630,690 ","3,269",,,,,,,,\r\n44,The Little Mermaid,"$296,989,468 ",26-May-23,"4,320",-,"$95,578,040 ","4,320",,,,,,,,\r\n45,The Little Mermaid,"$84,355,863 ",17-Nov-89,"1,533",-,"$6,031,914 ",994,,,,,,,,\r\n46,The Sixth Sense,"$293,506,292 ",6-Aug-99,"2,821",-,"$26,681,262 ","2,161",,,,,,,,\r\n47,Up,"$293,004,164 ",29-May-09,"3,886",160,"$68,108,790 ","3,766",7,"$293,004,164",3886,"$68,108,790",3766,"May 29, 2009",Walt Disney Studios Motion Pictures,pixar\r\n48,"The Chronicles of Narnia: The Lion, the Witch and the Wardrobe","$291,710,957 ",9-Dec-05,"3,853",153,"$65,556,312 ","3,616",,,,,,,,\r\n49,Monsters University,"$268,492,764 ",21-Jun-13,"4,004",181,"$82,429,469 ","4,004",8,"$268,492,764",4004,"$82,429,469",4004,"Jun 21, 2013",Walt Disney Studios Motion Pictures,pixar\r\n50,The Incredibles,"$261,441,092 ",5-Nov-04,"3,933",160,"$70,467,623 ","3,933",9,"$261,441,092",3933,"$70,467,623",3933,"Nov 5, 2004",Walt Disney Studios Motion Pictures,pixar\r\n51,Captain America: The Winter Soldier,"$259,766,572 ",4-Apr-14,"3,938",139,"$95,023,721 ","3,938",21,"$259,766,572",3938,"$95,023,721",3938,"Apr 4, 2014",Walt Disney Studios Motion Pictures,marvel\r\n52,"Monsters, Inc.","$255,873,250 ",2-Nov-01,"3,649",328,"$62,577,067 ","3,237",10,"$255,873,250",3649,"$62,577,067",3237,"Nov 2, 2001",Walt Disney Studios Motion Pictures,pixar\r\n53,Moana,"$248,757,044 ",23-Nov-16,"3,875",155,"$56,631,401 ","3,875",4,"$248,757,044",3875,"$56,631,401",3875,"Nov 23, 2016",Walt Disney Studios Motion Pictures,animated\r\n54,Toy Story 2,"$245,852,179 ",19-Nov-99,"3,257",244,"$300,163 ",1,11,"$245,852,179",3257,"$300,163",1,"Nov 19, 1999",Walt Disney Studios Motion Pictures,pixar\r\n55,Cars,"$244,082,982 ",9-Jun-06,"3,988",132,"$60,119,509 ","3,985",12,"$244,082,982",3988,"$60,119,509",3985,"Jun 9, 2006",Walt Disney Studios Motion Pictures,pixar\r\n56,Maleficent,"$241,410,378 ",30-May-14,"3,948",188,"$69,431,298 ","3,948",6,"$241,410,378",3948,"$69,431,298",3948,"May 30, 2014",Walt Disney Studios Motion Pictures,live reimaginings\r\n57,Pirates of the Caribbean: On Stranger Tides,"$241,071,802 ",20-May-11,"4,164",132,"$90,151,958 ","4,155",,,,,,,,\r\n58,Brave,"$237,283,207 ",22-Jun-12,"4,164",209,"$66,323,594 ","4,164",13,"$237,283,207",4164,"$66,323,594",4164,"Jun 22, 2012",Walt Disney Studios Motion Pictures,pixar\r\n59,Oz the Great and Powerful,"$234,911,825 ",8-Mar-13,"3,912",132,"$79,110,453 ","3,912",7,"$234,911,825",3912,"$79,110,453",3912,"Mar 8, 2013",Walt Disney Studios Motion Pictures,live reimaginings\r\n60,Doctor Strange,"$232,641,920 ",4-Nov-16,"3,882",132,"$85,058,311 ","3,882",22,"$232,641,920",3882,"$85,058,311",3882,"Nov 4, 2016",Walt Disney Studios Motion Pictures,marvel\r\n61,Signs,"$227,966,634 ",2-Aug-02,"3,453",188,"$60,117,080 ","3,264",,,,,,,,\r\n62,Shang-Chi and the Legend of the Ten Rings,"$224,543,292 ",3-Sep-21,"4,300",-,"$75,388,688 ","4,300",23,"$224,543,292",4300,"$75,388,688",4300,"Sep 3, 2021",Walt Disney Studios Motion Pictures,marvel\r\n63,WALL·E,"$223,808,164 ",27-Jun-08,"3,992",195,"$63,087,526 ","3,992",14,"$223,808,164",3992,"$63,087,526",3992,"Jun 27, 2008",Walt Disney Studios Motion Pictures,pixar\r\n64,Big Hero 6,"$222,527,828 ",7-Nov-14,"3,773",202,"$56,215,889 ","3,761",5,"$222,527,828",3773,"$56,215,889",3761,"Nov 7, 2014",Walt Disney Studios Motion Pictures,animated\r\n65,National Treasure: Book of Secrets,"$219,964,115 ",21-Dec-07,"3,832",181,"$44,783,772 ","3,832",,,,,,,,\r\n66,Ant-Man and the Wasp,"$216,648,740 ",6-Jul-18,"4,206",118,"$75,812,205 ","4,206",24,"$216,648,740",4206,"$75,812,205",4206,"Jul 6, 2018",Walt Disney Studios Motion Pictures,marvel\r\n67,Ant-Man and the Wasp: Quantumania,"$214,504,909 ",17-Feb-23,"4,345",118,"$106,109,650 ","4,345",25,"$214,504,909",4345,"$106,109,650",4345,"Feb 17, 2023",Walt Disney Studios Motion Pictures,marvel\r\n68,Solo: A Star Wars Story,"$213,767,512 ",25-May-18,"4,381",118,"$84,420,489 ","4,381",10,"$213,767,512",4381,"$84,420,489",4381,"May 25, 2018",Walt Disney Studios Motion Pictures,starwars\r\n69,Coco,"$210,460,015 ",22-Nov-17,"3,987",155,"$50,802,605 ","3,987",15,"$210,460,015",3987,"$50,802,605",3987,"Nov 22, 2017",Walt Disney Studios Motion Pictures,pixar\r\n70,Ratatouille,"$206,445,654 ",29-Jun-07,"3,940",167,"$47,027,395 ","3,940",16,"$206,445,654",3940,"$47,027,395",3940,"Jun 29, 2007",Walt Disney Studios Motion Pictures,pixar\r\n71,Thor: The Dark World,"$206,362,140 ",8-Nov-13,"3,841",160,"$85,737,841 ","3,841",26,"$206,362,140",3841,"$85,737,841",3841,"Nov 8, 2013",Walt Disney Studios Motion Pictures,marvel\r\n72,Armageddon,"$201,578,182 ",1-Jul-98,"3,184",-,"$36,089,972 ","3,127",,,,,,,,\r\n73,Cinderella,"$201,151,353 ",13-Mar-15,"3,848",188,"$67,877,361 ","3,845",8,"$201,151,353",3848,"$67,877,361",3845,"Mar 13, 2015",Walt Disney Studios Motion Pictures,live reimaginings\r\n74,Cinderella,"$10,000,000 ",4-Mar-50,-,-,-,-,8,"$201,151,353",3848,"$67,877,361",3845,"Mar 13, 2015",Walt Disney Studios Motion Pictures,live reimaginings\r\n75,Ralph Breaks the Internet,"$201,091,711 ",21-Nov-18,"4,017",141,"$56,237,634 ","4,017",6,"$201,091,711",4017,"$56,237,634",4017,"Nov 21, 2018",Walt Disney Studios Motion Pictures,animated\r\n76,Tangled,"$200,821,936 ",24-Nov-10,"3,603",190,"$48,767,052 ","3,603",7,"$200,821,936",3603,"$48,767,052",3603,"Nov 24, 2010",Walt Disney Studios Motion Pictures,animated\r\n77,Pearl Harbor,"$198,542,554 ",25-May-01,"3,255",-,"$59,078,912 ","3,214",,,,,,,,\r\n78,Toy Story,"$191,796,233 ",22-Nov-95,"2,574","3,210","$29,140,617 ","2,457",17,"$191,796,233",2574,"$29,140,617",2457,"Nov 22, 1995",Walt Disney Studios Motion Pictures,pixar\r\n79,Cars 2,"$191,452,396 ",24-Jun-11,"4,115",174,"$66,135,507 ","4,115",18,"$191,452,396",4115,"$66,135,507",4115,"Jun 24, 2011",Walt Disney Studios Motion Pictures,pixar\r\n80,Wreck-It Ralph,"$189,422,889 ",2-Nov-12,"3,752",181,"$49,038,712 ","3,752",8,"$189,422,889",3752,"$49,038,712",3752,"Nov 2, 2012",Walt Disney Studios Motion Pictures,animated\r\n81,Black Widow,"$183,651,655 ",9-Jul-21,"4,275",-,"$80,366,312 ","4,160",27,"$183,651,655",4275,"$80,366,312",4160,"Jul 9, 2021",Walt Disney Studios Motion Pictures,marvel\r\n82,Lincoln,"$182,207,973 ",9-Nov-12,"2,293",167,"$944,308 ",11,,,,,,,,\r\n83,Ant-Man,"$180,202,163 ",17-Jul-15,"3,868",153,"$57,225,526 ","3,856",29,"$180,202,163",3868,"$57,225,526",3856,"Jul 17, 2015",Walt Disney Studios Motion Pictures,marvel\r\n84,Pretty Woman,"$178,406,268 ",23-Mar-90,"1,811",-,"$11,280,591 ","1,325",,,,,,,,\r\n85,National Treasure,"$173,008,894 ",19-Nov-04,"3,243",195,"$35,142,554 ","3,017",,,,,,,,\r\n86,Pirates of the Caribbean: Dead Men Tell No Tales,"$172,558,876 ",26-May-17,"4,276",118,"$62,983,253 ","4,276",,,,,,,,\r\n87,TRON: Legacy,"$172,062,763 ",17-Dec-10,"3,451",118,"$44,026,211 ","3,451",,,,,,,,\r\n88,Mary Poppins Returns,"$171,958,438 ",19-Dec-18,"4,090",113,"$23,523,121 ","4,090",,,,,,,,\r\n89,Tarzan,"$171,091,819 ",16-Jun-99,"3,131",-,"$34,221,968 ","3,005",,,,,,,,\r\n90,The Help,"$169,708,112 ",10-Aug-11,"3,014",211,"$26,044,590 ","2,534",,,,,,,,\r\n91,Wild Hogs,"$168,273,550 ",2-Mar-07,"3,401",153,"$39,699,023 ","3,287",,,,,,,,\r\n92,Indiana Jones and the Dial of Destiny,"$168,257,021 ",30-Jun-23,"4,600",-,"$60,368,101 ","4,600",,,,,,,,\r\n93,Three Men and a Baby,"$167,780,960 ",25-Nov-87,"1,813",-,"$10,384,392 ","1,006",,,,,,,,\r\n94,Eternals,"$164,870,234 ",5-Nov-21,"4,090",-,"$71,297,219 ","4,090",31,"$164,870,234",4090,"$71,297,219",4090,"Nov 5, 2021",Walt Disney Studios Motion Pictures,marvel\r\n95,The Proposal,"$163,958,031 ",19-Jun-09,"3,158",139,"$33,627,598 ","3,056",,,,,,,,\r\n96,A Bug\'s Life,"$162,798,565 ",20-Nov-98,"2,773",181,"$291,121 ",1,19,"$162,798,565",2773,"$291,121",1,"Nov 20, 1998",Walt Disney Studios Motion Pictures,pixar\r\n97,The Waterboy,"$161,491,646 ",6-Nov-98,"2,782",-,"$39,414,071 ","2,664",,,,,,,,\r\n98,Who Framed Roger Rabbit,"$156,452,370 ",24-Jun-88,"1,598",-,"$11,226,239 ","1,045",,,,,,,,\r\n99,Cars 3,"$152,901,115 ",16-Jun-17,"4,256",139,"$53,688,680 ","4,256",20,"$152,901,115",4256,"$53,688,680",4256,"Jun 16, 2017",Walt Disney Studios Motion Pictures,pixar\r\n100,Elemental,"$146,233,801 ",16-Jun-23,"4,035",-,"$29,602,429 ","4,035",,,,,,,,\r\n101,Lilo & Stitch,"$145,794,338 ",21-Jun-02,"3,222",158,"$35,260,212 ","3,191",,,,,,,,\r\n102,The Santa Clause,"$144,833,357 ",11-Nov-94,"2,388",-,"$19,321,992 ","2,183",,,,,,,,\r\n103,The Chronicles of Narnia: Prince Caspian,"$141,621,490 ",16-May-08,"3,929",111,"$55,034,805 ","3,929",,,,,,,,\r\n104,Pocahontas,"$141,579,773 ",16-Jun-95,"2,757",-,"$2,689,714 ",6,,,,,,,,\r\n105,Sister Act,"$139,605,150 ",29-May-92,"2,087",-,"$11,894,587 ","1,430",,,,,,,,\r\n106,The Santa Clause 2,"$139,236,327 ",1-Nov-02,"3,352",97,"$29,008,696 ","3,350",,,,,,,,\r\n107,A Christmas Carol,"$137,855,863 ",6-Nov-09,"3,683",90,"$30,051,075 ","3,683",,,,,,,,\r\n108,Dinosaur,"$137,748,063 ",19-May-00,"3,319",-,"$38,854,851 ","3,257",,,,,,,,\r\n109,Ransom,"$136,492,681 ",8-Nov-96,"2,768",-,"$34,216,088 ","2,676",,,,,,,,\r\n110,101 Dalmatians,"$136,189,294 ",27-Nov-96,"2,901",-,"$33,504,025 ","2,794",9,"$136,189,294",2901,"$33,504,025",2794,"Nov 27, 1996",Walt Disney Studios Motion Pictures,live reimaginings\r\n111,Chicken Little,"$135,386,665 ",4-Nov-05,"3,658",160,"$40,049,778 ","3,654",,,,,,,,\r\n112,The Rock,"$134,069,511 ",7-Jun-96,"2,426",181,"$25,069,525 ","2,392",,,,,,,,\r\n113,Bringing Down the House,"$132,716,677 ",7-Mar-03,"2,910",174,"$31,101,026 ","2,801",,,,,,,,\r\n114,"Honey, I Shrunk the Kids","$130,724,172 ",23-Jun-89,"1,498",-,"$14,262,961 ","1,371",,,,,,,,\r\n115,Into the Woods,"$128,002,372 ",25-Dec-14,"2,833",112,"$31,051,923 ","2,440",,,,,,,,\r\n116,Enchanted,"$127,807,262 ",21-Nov-07,"3,730",113,"$34,440,317 ","3,730",,,,,,,,\r\n117,Sweet Home Alabama,"$127,223,418 ",27-Sep-02,"3,313",146,"$35,648,740 ","3,293",,,,,,,,\r\n118,"Good Morning, Vietnam","$123,922,370 ",25-Dec-87,"1,598",-,"$194,308 ",4,,,,,,,,\r\n119,The Good Dinosaur,"$123,087,120 ",25-Nov-15,"3,749",134,"$39,155,217 ","3,749",21,"$123,087,120",3749,"$39,155,217",3749,"Nov 25, 2015",Walt Disney Studios Motion Pictures,pixar\r\n120,Mulan,"$120,620,254 ",19-Jun-98,"2,953",-,"$22,745,143 ","2,888",,,,,,,,\r\n121,G-Force,"$119,436,770 ",24-Jul-09,"3,697",132,"$31,706,934 ","3,697",,,,,,,,\r\n122,Lightyear,"$118,307,188 ",17-Jun-22,"4,255",84,"$50,577,961 ","4,255",,,,,,,,\r\n123,Jungle Cruise,"$116,987,516 ",30-Jul-21,"4,310",-,"$35,018,731 ","4,310",,,,,,,,\r\n124,Remember the Titans,"$115,654,751 ",29-Sep-00,"2,803",-,"$20,905,831 ","1,865",,,,,,,,\r\n125,Dumbo,"$114,766,307 ",29-Mar-19,"4,259",132,"$45,990,748 ","4,259",10,"$114,766,307",4259,"$45,990,748",4259,"Mar 29, 2019",Walt Disney Studios Motion Pictures,live reimaginings\r\n126,The Village,"$114,197,520 ",30-Jul-04,"3,733",125,"$50,746,142 ","3,730",,,,,,,,\r\n127,Bolt,"$114,053,579 ",21-Nov-08,"3,654",93,"$26,223,128 ","3,651",9,"$114,053,579",3654,"$26,223,128",3651,"Nov 21, 2008",Walt Disney Studios Motion Pictures,animated\r\n128,Maleficent: Mistress of Evil,"$113,929,605 ",18-Oct-19,"3,820",118,"$36,948,713 ","3,790",11,"$113,929,605",3820,"$36,948,713",3790,"Oct 18, 2019",Walt Disney Studios Motion Pictures,live reimaginings\r\n129,The Pacifier,"$113,086,868 ",4-Mar-05,"3,181",132,"$30,552,694 ","3,131",,,,,,,,\r\n130,Enemy of the State,"$111,549,836 ",20-Nov-98,"2,517",-,"$20,038,573 ","2,393",,,,,,,,\r\n131,Freaky Friday,"$110,230,332 ",6-Aug-03,"3,067",162,"$22,203,007 ","2,954",,,,,,,,\r\n132,Freaky Friday,"$25,642,000 ",21-Jan-77,-,-,-,-,,,,,,,,\r\n133,Bedtime Stories,"$110,101,975 ",25-Dec-08,"3,684",77,"$27,450,296 ","3,681",,,,,,,,\r\n134,The Princess Diaries,"$108,248,956 ",3-Aug-01,"2,749",167,"$22,862,269 ","2,537",,,,,,,,\r\n135,George of the Jungle,"$105,263,257 ",18-Jul-97,"2,616",-,"$16,540,791 ","2

In [79]:
import os  
os.makedirs('data', exist_ok=True)  
disney_mylist_lmpssa.to_csv('data/mylist_lmpssa.csv')